### ISSUE TITLE
NullReferenceException in OracleInternal.ConnectionPool.PoolManager.AddPRToPool

### ISSUE THREAD

**Issue by niklaslundberg** [oracle/dotnet-db-samples#428] opened 2024-12-12 13:55 UTC
I've only seen this once in our  logs and I don't have any reproduction. Version 23.6.1.

The stack trace looks like this:

System.NullReferenceException: Object reference not set to an instance of an object.
   at OracleInternal.ConnectionPool.PoolManager`3.AddPRToPool(PR pr, Boolean bForPoolPopulation, Boolean migratePR)
   at OracleInternal.ConnectionPool.PoolManager`3.PutNewPR(PR pr, Boolean bForPoolPopulation)
   at OracleInternal.ConnectionPool.PoolManager`3.CreateNewPR(Int32 reqCount, Boolean bForPoolPopulation, ConnectionString csWithDiffOrNewPassw, OracleConnection connRefForCriteria, Boolean bIncrSemObtained, Boolean bMaxSemObtained, Boolean bIgnoreIdleSem, PMCNPR_RefAndOutParamArgCtx pmcnpr_refOutctx, String instanceName, List`1 switchFailedInstNames, Boolean bAsync)
   at OracleInternal.ConnectionPool.OraclePoolManager.CreateNewPR(Int32 reqCount, Boolean bForPoolPopulation, ConnectionString csWithDiffOrNewPassw, OracleConnection connRefForCriteria, Boolean bIncrSemObtained, Boolean bMaxSemObtained, Boolean bIgnoreIdleSem, PMCNPR_RefAndOutParamArgCtx pmcnpr_refOutctx, String instanceName, List`1 switchFailedInstNames, Boolean bAsync)
   at OracleInternal.ConnectionPool.PoolManager`3.Get(ConnectionString csWithDiffOrNewPassw, Boolean bGetForApp, OracleConnection connRefForCriteria, String affinityInstanceName, Boolean bForceMatch, Boolean bAsync)
   at OracleInternal.ConnectionPool.OraclePoolManager.Get(ConnectionString csWithNewPassw, Boolean bGetForApp, OracleConnection connRefForCriteria, String affinityInstanceName, Boolean bForceMatch, Boolean bAsync)
   at OracleInternal.ConnectionPool.PoolManager`3.WaitForPendingGet()
--- End of stack trace from previous location ---
   at OracleInternal.ConnectionPool.OracleConnectionDispenser`3.GetAsync(ConnectionString cs, PM conPM, ConnectionString pmCS, OracleOpaqueString securedPassw, OracleOpaqueString securedProxyPassw, OracleConnection connRefForCriteria, Boolean bAsync)
   at Oracle.ManagedDataAccess.Client.OracleConnectionInternal.OpenInternalAsync(Boolean bAsync)
   at Oracle.ManagedDataAccess.Client.OracleConnectionInternal.OpenAsyncHelper(CancellationToken cancellationToken)
   at Oracle.ManagedDataAccess.Client.OracleConnectionInternal.OpenAsync(CancellationToken cancellationToken)

**Comment by alexkeh** [comment] 2024-12-12 15:49
If the issue happened only once, it probably relies on some specific ODP.NET setting values, some load profile, and/or some database settings. That makes it especially hard to diagnose because we can't reproduce the problem reliably and diagnose the root cause.

If you can reliably reproduce the error, enable tracing and share the trace. That will give some insight on where the problem may be.

**Comment by alexkeh** [comment] 2024-12-23 23:47
Closing for now. I will reopen when we get a trace.

**Closed by alexkeh** 2024-12-23 23:47 UTC
