### ISSUE TITLE
Connecting to Autonomous Data Warehouse: Connection Timeout

### ISSUE THREAD

**Issue by derekssmith** [oracle/dotnet-db-samples#61] opened 2020-03-05 01:05 UTC
I am trying to use the sample code here: https://github.com/oracle/dotnet-db-samples/blob/master/samples/dotnet-core/autonomous-db/autonomous-odp-core.cs

However, I cannot connect successfully.  I just get a connection timeout.  I am using the same wallet with SQL Developer application and it works fine.

I enabled tracing on the driver and this is what I get.

```
2020-03-04 19:40:35.734043 TID:1   (CFG) (ENV)      Machine Name : <removed>
2020-03-04 19:40:35.739081 TID:1   (CFG) (ENV)      User Name : <removed>
2020-03-04 19:40:35.739284 TID:1   (CFG) (ENV)      OS Version : Unix 19.2.0.0
2020-03-04 19:40:35.739315 TID:1   (CFG) (ENV)      64-bit OS : True
2020-03-04 19:40:35.739329 TID:1   (CFG) (ENV)      64-bit Process : True
2020-03-04 19:40:35.739499 TID:1   (CFG) (ENV)      .NET Core Runtime Version : 3.1.0
2020-03-04 19:40:35.739520 TID:1   (CFG) (ENV)      Application Directory :  <removed>
2020-03-04 19:40:35.739533 TID:1   (CFG) (VER)      Oracle Data Provider for .NET Core Driver Version : 2.0.18.3
2020-03-04 19:40:35.749188 TID:1   (CFG) (VER)      Oracle Data Provider for .NET Core Driver Informational Version : 2.0.18.3:20180908
2020-03-04 19:40:35.749348 TID:1   (CFG) (.NET)     wallet_location :  <removed>
2020-03-04 19:40:35.749392 TID:1   (CFG) (.NET)     Resolved Trace File Location: /tmp/traces
2020-03-04 19:40:35.763268 TID:1   (PUB) (OCFG) OracleConfiguration.TraceFileLocation() : /tmp/traces
2020-03-04 19:40:35.763332 TID:1   (PUB) (OCFG) OracleConfiguration.TraceLevel() : 268435463
2020-03-04 19:40:35.763347 TID:1   (PUB) (OCFG) OracleConfiguration.TraceOption() : 1
2020-03-04 19:40:35.763358 TID:1   (PUB) (OCFG) OracleConfiguration.CommandTimeout() : 0
2020-03-04 19:40:35.763380 TID:1   (PUB) (OCFG) OracleConfiguration.DbNotificationPort() : -1
2020-03-04 19:40:35.763399 TID:1   (PUB) (OCFG) OracleConfiguration.DbNotificationAddress() : 
2020-03-04 19:40:35.763424 TID:1   (PUB) (OCFG) OracleConfiguration.BindByName() : False
2020-03-04 19:40:35.763436 TID:1   (PUB) (OCFG) OracleConfiguration.FetchSize() : 131072
2020-03-04 19:40:35.763448 TID:1   (PUB) (OCFG) OracleConfiguration.MaxStatementCacheSize() : -1
2020-03-04 19:40:35.763459 TID:1   (PUB) (OCFG) OracleConfiguration.SelfTuning() : True
2020-03-04 19:40:35.763469 TID:1   (PUB) (OCFG) OracleConfiguration.StatementCacheSize() : 0
2020-03-04 19:40:35.763480 TID:1   (PUB) (OCFG) OracleConfiguration.TnsAdmin() :  <removed>
2020-03-04 19:40:35.763496 TID:1   (PUB) (OCFG) OracleConfiguration.ServiceRelocationConnectionTimeout() : 90
2020-03-04 19:40:35.763507 TID:1   (PUB) (OCFG) OracleConfiguration.HAEvents() : True
2020-03-04 19:40:35.763517 TID:1   (PUB) (OCFG) OracleConfiguration.LoadBalancing() : True
2020-03-04 19:40:35.763527 TID:1   (PUB) (OCFG) OracleConfiguration.DrcpConnectionClass() : 
2020-03-04 19:40:35.763537 TID:1   (PUB) (OCFG) OracleConfiguration.DatabaseEditionName() : 
2020-03-04 19:40:35.763550 TID:1   (PUB) (OCFG) OracleConfiguration.WalletLocation() :  <removed>
2020-03-04 19:40:35.763566 TID:1   (PUB) (OCFG) OracleConfiguration.OnsConfigFile() : 
2020-03-04 19:40:35.764038 TID:1   (PUB) (OCFG) OracleConfiguration.OnsMode() : Unspecified
2020-03-04 19:40:35.773774 TID:1   (PUB) (ENT) OracleConnection.Open() (conid=55915408) (state=Closed) (sessid=0) (implid=0) (pooling=T) (txnid=n/a) 
2020-03-04 19:40:35.775896 TID:1   (PRI) (ENT) (CP) OracleConnectionDispenser..cctor()
2020-03-04 19:40:35.776334 TID:1   (PRI) (EXT) (CP) OracleConnectionDispenser..cctor()
2020-03-04 19:40:35.776360 TID:1   (PRI) (ENT) (CP) OracleConnectionDispenser.Get()
2020-03-04 19:40:35.777865 TID:1   (PRI) (ENT) (CP) PoolManager.ctor()
2020-03-04 19:40:35.778627 TID:1   (PRI) (EXT) (CP) PoolManager.ctor()
2020-03-04 19:40:35.779701 TID:1   (PRI) (ENT) (CP) PoolManager.Initialize() (constr=User Id=admin;Data Source=aw_medium;)
2020-03-04 19:40:35.783941 TID:1   (CFG) (SQLNET)   FilePath : (null)
2020-03-04 19:40:35.783978 TID:1   (CFG) (TNSNAMES) FilePath : <removed>/tnsnames.ora
2020-03-04 19:40:35.788192 TID:1   (CFG) (TNSNAMES) aw_high : (description= (retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1522)(host=adb.us-ashburn-1.oraclecloud.com))(connect_data=(service_name=<removed>))(security=(ssl_server_cert_dn="CN=adwc.uscom-east-1.oraclecloud.com,OU=Oracle BMCS US,O=Oracle Corporation,L=Redwood City,ST=California,C=US")))
2020-03-04 19:40:35.788282 TID:1   (CFG) (TNSNAMES) aw_low : (description= (retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1522)(host=adb.us-ashburn-1.oraclecloud.com))(connect_data=(service_name=<removed>))(security=(ssl_server_cert_dn="CN=adwc.uscom-east-1.oraclecloud.com,OU=Oracle BMCS US,O=Oracle Corporation,L=Redwood City,ST=California,C=US")))
2020-03-04 19:40:35.788322 TID:1   (CFG) (TNSNAMES) aw_medium : (description= (retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1522)(host=adb.us-ashburn-1.oraclecloud.com))(connect_data=(service_name=<removed>))(security=(ssl_server_cert_dn="CN=adwc.uscom-east-1.oraclecloud.com,OU=Oracle BMCS US,O=Oracle Corporation,L=Redwood City,ST=California,C=US")))
2020-03-04 19:40:35.793652 TID:1   (PRI) (EXT) (CP) PoolManager.Initialize() (pmid=27252167) (constr=User Id=admin;Data Source=aw_medium;)
2020-03-04 19:40:35.794663 TID:1   (PRI) (BUF) (OBP.CTOR) (poolid:43942917) (OracleConnectionDispenser`3.GetPM)
2020-03-04 19:40:35.797260 TID:1   (PRI) (ENT) (CP) OraclePoolManager.Get()
2020-03-04 19:40:35.824930 TID:1   (PRI) (ENT) (CP) PoolManager.Get() (txnid=n/a) (bForceMatch=F)
2020-03-04 19:40:35.825242 TID:1   (PRI) (ENT) (CP) PoolManager.Get() MultiTenant : Searching for a idle connection, retryCountWithoutAffinity: 0
2020-03-04 19:40:35.825658 TID:1   (PRI) (ENT) PoolManager.ProcessCriteriaCtx_NonEnlistedConnection()
2020-03-04 19:40:35.825683 TID:1   (PRI) (EXT) PoolManager.ProcessCriteriaCtx_NonEnlistedConnection()
2020-03-04 19:40:35.830823 TID:1   (PRI) (ENT) (CP) PoolManager.CreateNewPR() (txnid=n/a) 
2020-03-04 19:40:36.019332 TID:1   (PRI) (ENT) TimeStamp.GetLocalTZOffset()
2020-03-04 19:40:36.020558 TID:1   (PRI) (EXT) TimeStamp.GetLocalTZOffset()
2020-03-04 19:40:51.036466 TID:1   (PRI) (CP) PoolManager.CreateNewPR() (DUMP)
(CP) =================================
(CP) User Id=admin;Password=;Data Source=aw_medium;
(CP) pmid=
27252167(CP) =================================

2020-03-04 19:40:51.037959 TID:1   (PRI) (ENT) OracleException.ctor()
2020-03-04 19:40:51.038268 TID:1   (PRI) (ENT) OracleError.ctor()
2020-03-04 19:40:51.038420 TID:1   (PRI) (EXT) OracleError.ctor()
2020-03-04 19:40:51.038460 TID:1   (PRI) (EXT) OracleException.ctor()
2020-03-04 19:40:51.039213 TID:1   (PRI) (ENT) PoolManager.CreateNewPR()
2020-03-04 19:40:51.042888 TID:1   (PRI) (ERR) (CP) PoolManager.CreateNewPR() (txnid=n/a) Oracle.ManagedDataAccess.Client.OracleException (0x80004005): Connection request timed out
   at OracleInternal.ConnectionPool.PoolManager`3.CreateNewPR(Int32 reqCount, Boolean bForPoolPopulation, ConnectionString csWithDiffOrNewPwd, OracleConnection connRefForCriteria, String instanceName, List`1 switchFailedInstNames)
2020-03-04 19:40:51.042926 TID:1   (PRI) (EXT) PoolManager.CreateNewPR()
2020-03-04 19:40:51.043139 TID:1   (PRI) (EXT) (CP) PoolManager.CreateNewPR() (aff=n/a) (inst=) (affmatch=n/a) (pr.service=) (pr.pdb=) (pr.edition=) (sessid=-1:-1) (F;F;F;;N) (pmid=27252167) 
2020-03-04 19:40:51.043267 TID:1   (PRI) (EXT) (CP) PoolManager.Get() (txnid=n/a) PM.Get(aff=;force=F) returning (null)
2020-03-04 19:40:51.043314 TID:1   (PRI) (ENT) OraclePoolManager.Get()
2020-03-04 19:40:51.043486 TID:1   (PRI) (ERR) (CP) OraclePoolManager.Get() (txnid=n/a) Oracle.ManagedDataAccess.Client.OracleException (0x80004005): Connection request timed out
   at OracleInternal.ConnectionPool.PoolManager`3.Get(ConnectionString csWithDiffOrNewPwd, Boolean bGetForApp, OracleConnection connRefForCriteria, String affinityInstanceName, Boolean bForceMatch)
   at OracleInternal.ConnectionPool.OraclePoolManager.Get(ConnectionString csWithNewPassword, Boolean bGetForApp, OracleConnection connRefForCriteria, String affinityInstanceName, Boolean bForceMatch)
2020-03-04 19:40:51.043532 TID:1   (PRI) (EXT) OraclePoolManager.Get()
2020-03-04 19:40:51.043583 TID:1   (PRI) (EXT) (CP) OraclePoolManager.Get() (txnid=n/a) 
2020-03-04 19:40:51.044498 TID:1   (PRI) (ENT) OracleConnectionDispenser.Get()
2020-03-04 19:40:51.044619 TID:1   (PRI) (ERR) (CP) OracleConnectionDispenser.Get() (txnid=n/a) Oracle.ManagedDataAccess.Client.OracleException (0x80004005): Connection request timed out
   at OracleInternal.ConnectionPool.PoolManager`3.Get(ConnectionString csWithDiffOrNewPwd, Boolean bGetForApp, OracleConnection connRefForCriteria, String affinityInstanceName, Boolean bForceMatch)
   at OracleInternal.ConnectionPool.OraclePoolManager.Get(ConnectionString csWithNewPassword, Boolean bGetForApp, OracleConnection connRefForCriteria, String affinityInstanceName, Boolean bForceMatch)
   at OracleInternal.ConnectionPool.OracleConnectionDispenser`3.Get(ConnectionString cs, PM conPM, ConnectionString pmCS, SecureString securedPassword, SecureString securedProxyPassword, OracleConnection connRefForCriteria)
2020-03-04 19:40:51.044643 TID:1   (PRI) (EXT) OracleConnectionDispenser.Get()
2020-03-04 19:40:51.044699 TID:1   (PRI) (EXT) (CP) OracleConnectionDispenser.Get() (txnid=n/a) 
2020-03-04 19:40:51.044734 TID:1   (PRI) (ENT) OracleConnection.Open()
2020-03-04 19:40:51.044862 TID:1   (PUB) (ERR) OracleConnection.Open() (txnid=n/a) Oracle.ManagedDataAccess.Client.OracleException (0x80004005): Connection request timed out
   at OracleInternal.ConnectionPool.PoolManager`3.Get(ConnectionString csWithDiffOrNewPwd, Boolean bGetForApp, OracleConnection connRefForCriteria, String affinityInstanceName, Boolean bForceMatch)
   at OracleInternal.ConnectionPool.OraclePoolManager.Get(ConnectionString csWithNewPassword, Boolean bGetForApp, OracleConnection connRefForCriteria, String affinityInstanceName, Boolean bForceMatch)
   at OracleInternal.ConnectionPool.OracleConnectionDispenser`3.Get(ConnectionString cs, PM conPM, ConnectionString pmCS, SecureString securedPassword, SecureString securedProxyPassword, OracleConnection connRefForCriteria)
   at Oracle.ManagedDataAccess.Client.OracleConnection.Open()
2020-03-04 19:40:51.044890 TID:1   (PRI) (EXT) OracleConnection.Open()
2020-03-04 19:40:51.044964 TID:1   (PUB) (EXT) OracleConnection.Open() (conid=55915408) (state=Closed) (sessid=0) (implid=0) (pooling=T) (txnid=n/a) 

```

**Comment by alexkeh** [comment] 2020-03-05 01:40
Are you using macOS? There's a known issue with ADW wallets and macOS when using ODP.NET Core. This doesn't exist in SQL Developer since it doesn't use ODP.NET to connect.

The trace seems indicative of macOS Catalina (19.2).

**Comment by alexkeh** [comment] 2020-03-05 04:02
There's also a chance this may not be a SSL/TLS issue. Normally, we see another error when that is the case. Were there any other trace files generated? If so, can you share those?

**Comment by derekssmith** [comment] 2020-03-05 13:27
> Are you using macOS? There's a known issue with ADW wallets and macOS when using ODP.NET Core. This doesn't exist in SQL Developer since it doesn't use ODP.NET to connect.
> 
> The trace seems indicative of macOS Catalina (19.2).

Yes this is macOS Catalina.  I am going to run the code on a Windows machine for now.  Is there an issue or way to track when the macOS issue is fixed?

**Comment by alexkeh** [comment] 2020-03-05 16:24
Internally, Oracle is tracking this as Bug 29849626. We found that part of the problem arose from a [bug in .NET Core 2](https://github.com/dotnet/runtime/issues/29518). Microsoft fixed its bug in .NET Core 3. 

On the Oracle side, we're close to completing the fix. I'll know more in a couple weeks on the patch release timing.

With that said, the error you encounter is not the expected one when using macOS and TLS. There could be another issue. Let me know how the Windows testing goes.

**Comment by ScotMac** [comment] 2020-03-06 17:03
The problem Alex is referring to, a .NET Core problem with SSL/TLS on MacOS, is NOT a timeout. Thus it would be useful to get the trace for the thread that did the connection establishment, not just the connect pool thread.

Clarifications on Bug 29849626 that Alex brought up:
* Though we originally saw it for Core 2, it is ALSO associated with Core 3.
* The workaround that we have developed only fixing the problem is the application is targeting Core 3. ie, we don't have a workaround for Core 2 apps.

**Comment by alexkeh** [comment] 2020-04-19 04:09
Closing for now. We can reopen if we get the trace for the connection establishment thread.

On a side note, Bug 29849626 will be part of ODP.NET Core 19.7. The fix allows .NET Core 3 apps using ODP.NET Core on macOS to connect to Oracle Autonomous DB.

**Closed by alexkeh** 2020-04-19 04:09 UTC

**Comment by ScotMac** [comment] 2020-04-19 18:54
Note also, since it appears you are trying to connect to the cloud and are getting a timeout, one of the more common issues for such a scenario is a corporate firewall. ie, it may be the case that some intermediary server/proxy is dropping the connection establishment packet and thus causing the timeout. 

If there is such a proxy interfering with your connect, you can try using Oracle's "(HTTPS_PROXY=" and "(HTTPS_PROXY_PORT=" as a way to get though the proxy. You can read about it here:
https://docs.oracle.com/en/cloud/paas/autonomous-data-warehouse-cloud/user/connect-preparing.html#GUID-EFAFA00E-54CC-47C7-8C71-E7868279EF3B

**Comment by alexkeh** [comment] 2020-05-20 04:24
ODP.NET Core 19.7 was released a few weeks ago on NuGet Gallery.
