### ISSUE TITLE
Oracle EFCore 3.19.80 'System.DirectoryServices.Protocols' FileNotFoundException

### ISSUE THREAD

**Issue by Ser-Drephs** [oracle/dotnet-db-samples#99] opened 2020-09-17 09:37 UTC
On initializing the Oracle EFCore 3.19.80 we get the following Error message:
```
System.IO.FileNotFoundException: Could not load file or assembly 'System.DirectoryServices.Protocols, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Das System kann die angegebene Datei nicht finden.
File name: 'System.DirectoryServices.Protocols, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at OracleInternal.Network.LDAP..ctor(SqlNetOraConfig SNOConfig, Hashtable ObLdapHT)
   at OracleInternal.Network.AddressResolution.SetNewLDAP(Hashtable SQLNetHT, Hashtable LdapHT)
   at Oracle.ManagedDataAccess.Client.OracleConfiguration.set_TnsAdmin(String value)
```
We tried to narrow down the exception on our side, but found nothing.

Our nuget references
```xml
<ItemGroup>
        <PackageReference Include="AutoMapper" Version="9.0.0" />
        <PackageReference Include="AutoMapper.Extensions.ExpressionMapping" Version="3.1.1" />
        <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="7.0.0" />
        <PackageReference Include="Microsoft.AspNet.WebApi.Client" Version="5.2.7" />
        <PackageReference Include="Microsoft.AspNetCore.OData" Version="7.4.1" />
        <PackageReference Include="Microsoft.AspNetCore.SpaServices" Version="3.1.8" />
        <PackageReference Include="Microsoft.AspNetCore.SpaServices.Extensions" Version="3.1.8" />
        <PackageReference Include="Microsoft.CodeAnalysis" Version="3.6.0" />
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="3.6.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.1.8" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" Version="3.1.8" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Analyzers" Version="3.1.8" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="3.1.8" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="3.1.8" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite.Core" Version="3.1.8" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.1.8">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="3.1.8">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.1.8" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="3.1.8" />
        <PackageReference Include="Microsoft.Extensions.Configuration" Version="3.1.8" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="3.1.8" />
        <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="3.1.8" />
        <PackageReference Include="Microsoft.Extensions.Logging" Version="3.1.8" />
        <PackageReference Include="Microsoft.Win32.Registry" Version="4.7.0" />
        <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
        <PackageReference Include="Oracle.EntityFrameworkCore" Version="3.19.80" />
        <PackageReference Include="Scrutor" Version="3.2.1" />
        <PackageReference Include="Serilog.AspNetCore" Version="3.4.0" />
        <PackageReference Include="Serilog.Enrichers.Environment" Version="2.1.3" />
        <PackageReference Include="Serilog.Enrichers.Process" Version="2.0.1" />
        <PackageReference Include="Serilog.Enrichers.Thread" Version="3.1.0" />
        <PackageReference Include="Serilog.Exceptions" Version="5.6.0" />
        <PackageReference Include="Serilog.Formatting.Compact" Version="1.1.0" />
        <PackageReference Include="Serilog.Sinks.File" Version="4.1.0" />
        <PackageReference Include="Serilog.Sinks.Map" Version="1.0.1" />
        <PackageReference Include="Serilog.Sinks.EventLog" Version="3.1.0" />
        <PackageReference Include="System.Configuration.ConfigurationManager" Version="4.7.0" />
        <PackageReference Include="System.Data.SqlClient" Version="4.8.1" />
        <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="6.6.0" />
        <PackageReference Include="System.IO.Abstractions" Version="11.0.10" />
        <PackageReference Include="System.Text.Encoding.CodePages" Version="4.7.1" />
    </ItemGroup>
```
Is that a known issue?

**Comment by Ser-Drephs** [comment] 2020-09-17 13:56
There is already an issue in the community board: (https://community.oracle.com/thread/4345086)

**Comment by alexkeh** [comment] 2020-09-17 14:24
This bug has been fixed recently and will be part of our next ODP.NET 19.10 release.

**Comment by alexkeh** [comment] 2020-09-17 14:36
This issue is the same root cause as [Issue 97](https://github.com/oracle/dotnet-db-samples/issues/97)

**Comment by alexkeh** [comment] 2020-09-17 17:13
While you're waiting for a fix, there are a couple workarounds. You can either:
1) Include the System.DirectoryServices.Protocols NuGet package or
2) Don't set TnsAdmin via OracleConfiguration. Use other means to get the configuration info.

**Comment by alexkeh** [comment] 2020-10-22 06:42
The bug fix is available as ODP.NET Core 2.19.91 on NuGet Gallery.

**Closed by alexkeh** 2020-10-22 06:42 UTC
Labels: duplicate
