### ISSUE TITLE
"DELETE RETURNING BULK COLLECT collect INTO" don't return value

### ISSUE THREAD

**Issue by hyabean** [oracle/dotnet-db-samples#265] opened 2022-11-11 03:18 UTC
"DELETE RETURNING BULK COLLECT collect INTO" behaviour different from "Update RETURNING BULK COLLECT collect INTO".  p.Value doesn't contain any item when executing "DELETE" WHILE "UPDATE" does.

```		// string create table sql: "
		//CREATE TABLE NEWSADMIN.TestTable(
		//	MainId NUMBER NULL,
		//	SECUCODE VARCHAR2(500) NULL
		//); "

//		cmd.CommandText =
//		@"
//BEGIN UPDATE NEWSADMIN.TestTable SET MainId = 123 WHERE SECUCODE = '1111112' RETURNING MainId bulk collect INTO :o_MainId;
//END;";

		cmd.CommandText =
		@"
BEGIN delete FROM NEWSADMIN.TestTable WHERE SECUCODE = '1111112' RETURNING MainId bulk collect INTO :o_MainId;
END;";

		cmd.CommandType = CommandType.Text;
		cmd.BindByName = true;
		cmd.ArrayBindCount = 50;
		var p = cmd.CreateParameter();
		p.ParameterName = "o_MainId";
		p.Direction = ParameterDirection.Output;
		p.OracleDbType = OracleDbType.Int32;
		p.Size = 100;
		p.CollectionType = OracleCollectionType.PLSQLAssociativeArray;
		cmd.Parameters.Add(p);

		var cnt = cmd.ExecuteNonQuery();
		
		// Check result
		//Console.WriteLine(p.Value);
		var value = p.Value as OracleDecimal[];
		
		foreach (var item in value)
		{
			Console.WriteLine(item.ToInt32());
		}
```

Version: All. Include Oracle.ManagedDataAccess.Core 3.21.80 and Oracle.ManagedDataAccess 21.8.0. 

Tested in pl/sql, the below code print the result.
`declare
type tt_EOCSINNERID is table of number;
o_EOCSINNERID tt_EOCSINNERID;
BEGIN DELETE NEWSADMIN.TestTable WHERE "SECUCODE" = '1111112' RETURNING MainId bulk collect INTO o_EOCSINNERID;
for i in o_EOCSINNERID.FIRST .. o_EOCSINNERID.last loop
    dbms_output.put_line('ROWID of updated row '||o_EOCSINNERID(i));
end LOOP;
END;`

**Comment by alexkeh** [comment] 2022-11-13 00:42
Thanks for reporting! I was able to reproduce this issue with ODP.NET Core 21.8. I have filed bug 34793217 to track it.

**Comment by hyabean** [comment] 2022-11-14 10:48
> Thanks for reporting! I was able to reproduce this issue with ODP.NET Core 21.8. I have filed bug 34793217 to track it.

Will it be fixed next version? Can I raise the priority in MOS?

**Comment by alexkeh** [comment] 2022-11-14 14:56
It's too early to say when a fix will be available. The Dev team needs to understand the root cause and figure out how to fix it. If you need the fix expedited, you can make that request in MOS.

In general, ODP.NET releases patches at least once a quarter. Every fix that makes the merge deadline will be included in the next quarterly patch. It's possible to get a fix sooner with a one-off patch request if the problem affects your production system or there's some other time critical need.

**Comment by alexkeh** [comment] 2022-11-22 15:31
@hyabean Can you try commenting out the following line and re-executing your DELETE scenario?

`// cmd.ArrayBindCount = 50;`

ArrayBindCount is intended for use with parameter array binding, not PL/SQL associative arrays. That is likely to fix your issue.

**Comment by hyabean** [comment] 2022-12-08 11:13
@alexkeh It works. But why does this only affect the DELETE statement, while the UPDATE statement works as expected?

**Comment by alexkeh** [comment] 2022-12-08 16:37
I didn't get an explanation why from my dev team. Fundamentally, ArrayBindCount shouldn't affect associative arrays. But because it's not intended to be used with ArrayBindCount, there probably aren't tests to check for these type of artifacts that could occur.

**Closed by alexkeh** 2022-12-08 16:37 UTC
Labels: bug
