### ISSUE TITLE
OracleDbType.TimeStampTZ is mapped to DbType.DateTime instead of DbType.DateTimeOffset

### ISSUE THREAD

**Issue by hazevich** [oracle/dotnet-db-samples#121] opened 2020-11-12 13:31 UTC
Hi, 

as the title says `OracleDbType.TimeStampTZ` is mapped to `DbType.DateTime` instead of `DbType.DateTimeOffset`.

If to assign `OracleDbType` on `OracleParameter` without assigning `DbType`:
```
var oracleParameter = new OracleParameter();
oracleParameter.OracleDbType = OracleDbType.TimeStampTZ;
```
`oracleParameter.DbType` then returns `DbType.DateTime` instead of `DbType.DateTimeOffset`.

**Comment by alexkeh** [comment] 2020-11-13 00:53
@hazevich 
Thanks for reporting this issue. I've reproduced it and have created a bug (32148810) to track the issue.

**Comment by alexkeh** [comment] 2022-09-27 22:13
This turns out to be a documentation bug. `OracleDbType.TimeStampTZ` is intended to be mapped to `DbType.DateTime`. We'll have this fixed in the next doc iteration for ODP.NET 21.8.

**Closed by alexkeh** 2022-09-27 22:13 UTC
Labels: bug

**Comment by tchanturia** [comment] 2022-09-30 07:55
How come is this by design? Oracle `TimeStampTZ` has time zone information and .NET `DateTime` does not have that, unlike `DateTimeOffset`.

**Comment by alexkeh** [comment] 2022-10-01 02:10
The reason is historical. When .NET FW was introduced 20+ years ago, it didn't have DateTimeOffset. ODP.NET was first designed without DateTimeOffset available, but Oracle DB data types needed to be mapped to some .NET type. For the TimeStampTZ, DateTime provided the best fit at the time. There were some circumstances that we left DateTime mapping in place so as not to break existing apps.

Looking at the original bug report, I may have misunderstood what the original poster meant. It's not clear to me what they are doing. The code binds a parameter as 
`oracleParameter.OracleDbType = OracleDbType.TimeStampTZ;`

Then it tries to use a `DbType` instead. Why not bind the parameter as a `DbType.DateTimeOffset` if the intent is to retrieve it as that data type?
