### ISSUE TITLE
Cursor Overflow ODP.NET not fixed with 8.21.140

### ISSUE THREAD

**Issue by JK-404** [oracle/dotnet-db-samples#385] opened 2024-05-31 07:57 UTC
After upgrading the ODP.NET Version to 8.21.140 we still encountering the open cursor issue. 
We getting a lot of data once a day (about 8000 requests) after this there is nearly no traffic on the service. The cursors are staying open until the next day this repeats until the database cursor limit is exceeded.

Database: Oracle 19.17.0.0.0

```<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Oracle.EntityFrameworkCore" Version="8.21.140" />
  </ItemGroup>

</Project>
```

**Connection String**
`CONNECTION_STRING: "Data Source=(DESCRIPTION=(ENABLE=BROKEN)(ADDRESS=(PROTOCOL=TCP)(HOST=www.wasserwerfer.com)(PORT=1541))(CONNECT_DATA=(SERVER=dedicated)(SERVICE_NAME=wasserwerfer)));User Id=((DB_USER));Password=((DB_PWD))"`

**Comment by alexkeh** [comment] 2024-05-31 15:19
@JK-404 For cursor leaks, we'll likely need at least the Oracle EF Core test case that reproduces the issue. Sometimes leaks are caused by a bug in the DB server, sometimes in the client driver, and sometimes in the app code that do not explicitly close/dispose objects they have completed their work with.

The challenge increases if the cursor leak requires a certain amount of load to occur.

It's generally easier if you open an Oracle Support service request in these situations if expediency is important. The Oracle analyst can examine your setup directly and conduct some diagnostics and review the code.

**Comment by alexkeh** [comment] 2024-06-11 16:15
Closing for now. Will reopen once we get more diagnostics.

**Closed by alexkeh** 2024-06-11 16:15 UTC
