### ISSUE TITLE
Pagination over large tables slow

### ISSUE THREAD

**Issue by iulianb** [oracle/dotnet-db-samples#106] opened 2020-10-08 13:32 UTC
There is a significant performance drop in Oracle's adapter for EF Core compared to EF6 when selecting from a table with 2 million rows. EF6 is using a different approach for computing the row number required for paging. 

EF6
```
SELECT * 
FROM ( 
SELECT 
"Extent1"."Id" AS "Id"
FROM ( SELECT "Extent1"."Id" AS "Id", row_number() OVER (ORDER BY "Extent1"."Id" DESC) AS "row_number"
	FROM "Table" "Extent1"
)  "Extent1"
WHERE ("Extent1"."row_number" > :p__linq__0)
ORDER BY "Extent1"."ID" DESC
)
WHERE (ROWNUM <= (:p__linq__1))
```

EF Core
```
Select
 K0 "Id"
 from (
  select 
    "m2".*, 
    rownum r2 
  from
    (
    SELECT "t"."Id" K0
    FROM "Table" "t"

    ORDER BY "t"."Id" DESC
    ) "m2"
) "m1"
where r2 > :p_0
and r2 <= (:p_0 + :p_1)

```
I am using Oracle 11g (11.2.0.3.0) and have set compatibility level to 11 when configuring the DbContext.

**Comment by alexkeh** [comment] 2020-10-08 17:53
@iulianb Can you provide a reproducible test case that contains the model and LINQ? My team can then take a look.

Does the slow performance occur with EF Core 2.x or 3.x?

**Comment by iulianb** [comment] 2020-10-09 08:40
@alexkeh  

We're using EF Core 3.x.

I've created a private repository and sent you an invite. If it's relevant/mandatory I can make the repository public. Let me know if there's anything else I should provide.

**Comment by alexkeh** [comment] 2020-10-09 15:47
@iulianb Got it. We'll take a look.

**Comment by alexkeh** [comment] 2020-10-09 23:15
I've filed bug 31997288 to track this issue.

@iulianb We will try to reproduce the issue in house. Since it's a performance issue, how much slower is the execution vs. EF 6?

**Comment by iulianb** [comment] 2020-10-10 16:22
@alexkeh ~50ms on EF6 vs ~4-5s on EF Core

**Comment by iulianb** [comment] 2020-11-17 06:50
@alexkeh we're trying to find the bug in oracle support but we're not able to find it

**Comment by alexkeh** [comment] 2020-11-17 16:26
@iulianb I just toggled the bug status to public from internal. Within 24 hours, you should be able to view the bug from MOS.

**Comment by Giorgi** [comment] 2021-01-21 18:23
Is there any update on this issue?

**Comment by alexkeh** [comment] 2021-01-21 20:27
I don't have an update. The dev team has been focused on .NET 5 and EF Core 5 support the past few months. I'll ask if they can provide an update.

**Comment by alexkeh** [comment] 2021-02-17 00:07
No update yet. The team had been busy with delivering the EFC5 release and 21c. I'll ask again.

**Comment by Giorgi** [comment] 2021-02-26 14:07
@alexkeh 

We were to replicate this issue as well. Additionally, when running against Oracle Database 12c the generated query is:

```SELECT *
FROM documents dd
ORDER BY dd.doc_key
OFFSET 100 ROWS FETCH NEXT 20 ROWS ONLY;

that results in `TABLE ACCESS STORAGE FULL` instead of using index on doc_key column as EF 6 did. This results in huge query time and prevents us from moving .Net Framework to .Net 5.

**Comment by Giorgi** [comment] 2021-03-26 22:50
@alexkeh Still no update on this issue? This is a major regression from EF 6 to EF Core.

**Comment by alexkeh** [comment] 2021-03-27 15:06
@Giorgi I didn't get an update last time I asked. I've asked again.

Was the performance significantly better with EF Core 2.1 for you? The OP indicated the performance difference was between EF6 and EF Core. I wasn't aware there was a performance difference between an earlier EF Core that would make this a regression.

**Comment by Giorgi** [comment] 2021-03-27 15:30
I haven't tried earlier versions of EF Core so I don't know but it was a lot faster with EF 6

**Comment by alexkeh** [comment] 2021-03-29 16:25
@Giorgi Are you using the same test case as the OP to reproduce the error? My dev team plans to focus on the OP's test case to diagnose, fix the issue, and then verify the fix resolves the performance problem. If your test case produces a different bug, then it may not get resolved if we fix the first issue. If it's a different bug, provide a test case if you can. Thanks!

**Comment by Giorgi** [comment] 2021-03-29 17:21
@alexkeh My test case is exactly the same with the only difference being that we run on Oracle 12 so the SQL produced by EF Core is different from what the OP posted but the end result is the same: The EF Core query does a full table scan and takes a lot of time.

The query generated by EF Core when running on Oracle 12 is:

```
SELECT *
FROM documents dd
ORDER BY dd.doc_key
OFFSET 100 ROWS FETCH NEXT 20 ROWS ONLY;
```

If you need more details I will try to get them to you.

**Comment by alexkeh** [comment] 2021-04-20 15:01
@iulianb 

My dev team tried to reproduce the issue using the test case provided. It had the following table definition:
```
CREATE TABLE "ORDERS" 
(             
  "SID" NUMBER(16,0) NOT NULL ENABLE, 
  "ID" VARCHAR2(18 CHAR) NOT NULL ENABLE
)
```
Here is the analysis-
- The table definition does not have primary key, so by default it won’t have any index created for any column.
- We ran the test case with EF6 and EFCore, but were not able to reproduce the issue. We find that EFCore is a bit faster than EF6 (4 sec vs 5 sec approximately).
- We tried to see the execution plan of generated query. Both EF6 query and EFCore query were using the ‘TABLE ACCESS FULL’ scan.
- If we create an index on the ID column manually, both EF6 and EFCore query is a lot faster as they both uses INDEX SCAN.
- We verified from sqlplus that  ‘TABLE ACCESS FULL’ scan takes around 1.2 sec to get the result and INDEX scan takes around 50 ms.

As such, we are NOT able to reproduce the issue. We are not sure why you are facing a different execution plan for EF6 vs EFCore query. As it seems the problem is with different execution plan.

When we do see a change in execution plans in EF Core, it often occurs when a .NET String entity property bind data type and the database column data type Unicode support do not match. This can happen when performing a string comparison between a Unicode and non-Unicode type. In those cases, we do see full table scans occurring when it is not expected. Here are more details about [Oracle EF Core performance issues to evaluate](https://docs.oracle.com/en/database/oracle/oracle-data-access-components/19.3.2/odpnt/EFCorePerformanceConsiderations.html).

Let me know if we're missing anything specific in the test case that's necessary to reproduce this performance issue.

**Comment by Giorgi** [comment] 2021-04-20 15:21
@alexkeh What was the linq query that you tested? This has nothing to do with Unicode vs Non Unicode strings, this happens when you use Skip/Take in a query

**Comment by alexkeh** [comment] 2021-04-20 15:45
@Giorgi 

I was pointing out the other common performance issue we've seen when the execution plans change unexpectedly. 

Here's the LINQ itself that was part of the test case:
`            var orders = context.Set<Order>().OrderByDescending(o => o.Number).Skip(20).Take(10).ToList();`

**Comment by Giorgi** [comment] 2021-04-20 15:49
The execution plan is different in our case because the generated query is different. We don't do ordering or filtering on a VarChar column.

**Comment by alexkeh** [comment] 2021-04-27 15:58
Is there another test case or more details for the current test case that can reproduce this performance issue? My team is unable to reproduce slower performance in EF Core vs. EF6 with the current test case.

**Comment by Giorgi** [comment] 2021-04-27 16:13
I will provide a repro in the next few days.

**Comment by Giorgi** [comment] 2021-05-09 14:30
@alexkeh I'm working on repro right now. Will share it with you today.

**Comment by Giorgi** [comment] 2021-05-10 10:35
@alexkeh Just invited you to a private repo with repro code.

**Comment by alexkeh** [comment] 2021-05-10 13:47
Got the repro. We'll take a look.

**Comment by Giorgi** [comment] 2021-05-28 16:55
@alexkeh Did you gather statistics on the table before getting the query plan as included in the demo? The EF Core query generates full table scan only after gathering statistics.

**Comment by alexkeh** [comment] 2021-06-03 13:30
@Giorgi 

Yes, we ran the .NET test application as provided. It executed the stored procedure to gather the statistics, then it executed the query. We have verified this using SQLPlus also.

SQL> exec DBMS_STATS.GATHER_TABLE_STATS('CIB', '"TestTablesEFCore"');
PL/SQL procedure successfully completed.

SQL> var p_0 number;
SQL> var p_1 number;
SQL> begin
  2  :p_0 := 100;
  3  :p_1 := 50;
  4  end;
  5  /
PL/SQL procedure successfully completed.

SQL> explain plan for
  2  SELECT "t"."TestTableKey", "t"."TestTableText"
  3  FROM "CIB"."TestTablesEFCore" "t"
  4  ORDER BY "t"."TestTableKey"
  5  OFFSET :p_0 ROWS FETCH NEXT :p_1 ROWS ONLY;
  
Explained.

SQL> select plan_table_output from table(dbms_xplan.display('plan_table',null,'basic'));

PLAN_TABLE_OUTPUT
--------------------------------------------------------------------------------
Plan hash value: 788034004

-------------------------------------------------------------
| Id  | Operation                      | Name               |
-------------------------------------------------------------
|   0 | SELECT STATEMENT               |                    |
|   1 |  VIEW                          |                    |
|   2 |   WINDOW NOSORT STOPKEY        |                    |
|   3 |    FILTER                      |                    |
|   4 |     TABLE ACCESS BY INDEX ROWID| TestTablesEFCore   |
|   5 |      INDEX FULL SCAN           | TESTTABLESEFCOREPK |

PLAN_TABLE_OUTPUT

**Comment by alexkeh** [comment] 2023-01-06 22:57
Closing issue without a test case to diagnose with. It's possible with the upgrade to EFC 6 that the performance issue was resolved. We're unable to reproduce the slow performance.

**Closed by alexkeh** 2023-01-06 22:57 UTC
Labels: bug, enhancement
