### ISSUE TITLE
SaveChanges() return 0 for id

### ISSUE THREAD

**Issue by rogerskk** [oracle/dotnet-db-samples#27] opened 2019-03-28 23:50 UTC
When using SaveChanges() to add an item to a table, I get a 0 back for the unique id.  When I check in the Oracle database, it shows a number for the id and was inserted fine.  I am just not getting the id back after calling SaveChanges() in my code.

**Comment by alexkeh** [comment] 2019-03-29 13:07
SaveChanges() returns the number of rows affected, rather than a unique id. I would expect that if you did change one row, you would receive back a value of 1, however.

Which EF version are you using?
Are you using ODP.NET managed, unmanaged, or Core?
Which ODP.NET version are you using?

**Comment by rogerskk** [comment] 2019-03-29 14:34
I am using core.  I'm doing the following:
 orContext.PWebServiceRequestOracle.Add(newrecord);
                        orContext.Entry(newrecord).State = EntityState.Added;                        
                        orContext.SaveChanges();
                        liRecordID = newrecord.Id;
liRecordID is 0, but the record is added to the database, but it seems that they don't commit.

**Comment by alexkeh** [comment] 2019-03-29 16:32
@rogerskk 

I tried your code using the following GitHub sample with Oracle EF Core Beta 2:
https://github.com/oracle/dotnet-db-samples/blob/master/samples/dotnet-core/ef-core/create-model-save-query.cs

I replaced the code updating the Blogs table with the following code instead to emulate what you are doing:
            using (var db = new BloggingContext())
            {
                var blog = new Blog { Url = "https://blogs.oracle.com" };
                db.Blogs.Add(blog);
                db.Entry(blog).State = EntityState.Added;
                db.SaveChanges();
                int i = blog.BlogId;
            }

The application inserts one row entry and returns the value 1 for the "i" variable, which is what I expected.

Are you using the Oracle EF Core beta 2 (i.e. 2.18.0-beta2)? Perhaps the insert requires some other operation to occur for the bug to reproduce.

**Comment by rogerskk** [comment] 2019-03-29 16:34
Yes, I'm uisng the beta2.

**Comment by alexkeh** [comment] 2019-03-29 16:38
You can email me a more complete test case if you'd like. You should have my email from the beta invitation.

In the email, let me know what DB version you are working with and the EF Core version.

**Comment by alexkeh** [comment] 2019-04-01 17:42
Closing this issue.

The problem was resolved by using Entity Framework Core 2.2.3. Originally, Entity Framework 6.2.0 was being used. Oracle doesn't currently support EF 6 on .NET Core.

**Closed by alexkeh** 2019-04-01 17:42 UTC
