### ISSUE TITLE
Support for EF Core 8.0

### ISSUE THREAD

**Issue by mkstephenson** [oracle/dotnet-db-samples#328] opened 2023-11-15 10:30 UTC
Since EF Core 8.0 was released yesterday, we were wondering when the Oracle.EntityFrameworkCore package will be adding support for EF Core 8.0?

**Comment by alexkeh** [comment] 2023-11-15 15:44
We're currently setting up and running our ODP.NET test suites with the new EF Core 8 bits. The official Oracle EF Core 8 release will be available by the end of the year.

**Comment by mkstephenson** [comment] 2023-11-16 08:32
Ok, it would be great to be kept up to date on this since this is currently blocking our migration to .NET 8.

**Comment by alexkeh** [comment] 2023-11-16 16:11
@mkstephenson You can subscribe to this GItHub thread. I will announce when Oracle EF Core 8 support becomes available here and close the issue.

Alternatively, you can subscribe to the Oracle .NET twitter feed for the announcement: https://twitter.com/oracledotnet

**Comment by LucaCris** [comment] 2023-11-30 13:28
Confirmed NET 8 migration suspended due to lack of Oracle EF8 support... _End of the year_ is too far away, to start well with our products in January!

**Comment by mkstephenson** [comment] 2023-11-30 13:51
> > Confirmed NET 8 migration suspended due to lack of Oracle EF8 support... _End of the year_ is too far away, to start well with our products in January!
> 
> I agree. Oracle is _ALWAYS_ the hold up for us unfortunately

Agreed, when I told my team we wouldn't be able to upgrade to .NET 8 because of Oracle, the reaction was along the lines of "no surprises there".

**Comment by lwestfall** [comment] 2023-11-30 14:56
> Confirmed NET 8 migration suspended

> we wouldn't be able to upgrade to .NET 8 because of Oracle

Folks, you know you can still migrate to .NET 8, right? You can't migrate to **EF Core** 8, but that's separate. You can target .NET 8 and still run EF Core 7 until Oracle releases their EF Core 8 packages. You're allowed to be frustrated, but be frustrated for the right reasons.

**Comment by IonRobu** [comment] 2023-11-30 15:00
> > Confirmed NET 8 migration suspended
> 
> > we wouldn't be able to upgrade to .NET 8 because of Oracle
> 
> Folks, you know you can still migrate to .NET 8, right? You can't migrate to **EF Core** 8, but that's separate. You can target .NET 8 and still run EF Core 7 until Oracle releases their EF Core 8 packages. You're allowed to be frustrated, but be frustrated for the right reasons.

I also upgraded my projects to .NET8 and kept all my Microsoft.EntityFrameworkCore.* packages to 7.0.3 version and is working fine with version 7.21.12 of Oracle.EntityFrameworkCore

**Comment by mkstephenson** [comment] 2023-11-30 15:36
> > Confirmed NET 8 migration suspended
> 
> > we wouldn't be able to upgrade to .NET 8 because of Oracle
> 
> Folks, you know you can still migrate to .NET 8, right? You can't migrate to **EF Core** 8, but that's separate. You can target .NET 8 and still run EF Core 7 until Oracle releases their EF Core 8 packages. You're allowed to be frustrated, but be frustrated for the right reasons.

Good point, I totally forgot that was a possibility in the middle of all of my NuGet package conflicts... now I feel like a bit of a fool 😅

**Comment by alexkeh** [comment] 2023-12-08 03:46
Oracle EF Core 8 now available: https://www.nuget.org/packages/Oracle.EntityFrameworkCore/8.21.121

**Closed by alexkeh** 2023-12-08 03:46 UTC
Labels: enhancement

**Comment by marcmognol** [comment] 2023-12-08 13:34
> Oracle EF Core 8 now available: https://www.nuget.org/packages/Oracle.EntityFrameworkCore/8.21.121

Great.
Could you please confirm that this new version doesn't support Oracle 11? Thanks

Marc

**Comment by alexkeh** [comment] 2023-12-08 14:58
@marcmognol That's correct. Oracle EF Core 8 only supports DB 19c and higher versions as [documented in the Oracle EF Core 8 blog post announcement](https://medium.com/oracledevs/announcing-oracle-entity-framework-core-8-19a084d0e20b).

**Comment by marcmognol** [comment] 2023-12-08 14:59
Thank you. Marc

**Comment by jlvsistemas** [comment] 2023-12-08 16:59
There is any prevision to support Oracle 11.2 and 12? I have several clients that still use 11.2 and 12.

**Comment by LucaCris** [comment] 2023-12-12 14:32
Tested successfully, all my solution is now NET8, EF.Oracle OK...

**Comment by jonyustc** [comment] 2023-12-17 05:44
oracle efcore 8 facing scaffolding not working issue

**Comment by alexkeh** [comment] 2023-12-17 14:48
@jonyustc Do you want to share your scaffolding trace file to diagnose the problem?

**Comment by BartNSTCL** [comment] 2024-01-02 15:22
I have *.21.121 installed, along with Oracle.MangedDataAccess.Core 23.3.1-dev. Whats the timeline on Oracle,EntityFrameworkCore updating to resolve the warning

warning NU1608: Detected package version outside of dependency constraint: Oracle.EntityFrameworkCore 8.21.121 requires Oracle.ManagedDataAccess.Core (>= 3.21.120 && < 3.22.0) but version Oracle.ManagedDataAccess.Core 23.3.1-dev was resolved

**Comment by alexkeh** [comment] 2024-01-02 15:46
@BartNSTCL Any reason you can't use ODP.NET Core 3.21.130? Is the question just about resolving the warning message or about a production supported release with 23c?

Version 23.3.1-dev is a non-production version. Version 8.21.121 is a production release.

**Comment by BartNSTCL** [comment] 2024-01-02 15:49
> @BartNSTCL Any reason you can't use ODP.NET Core 3.21.130? Is the question just about resolving the warning message or about a production supported release with 23c?
> 
> Version 23.3.1-dev is a non-production version. Version 8.21.121 is a production release.

I just have my Nugets set to Include Dev since there are some I use I need that. So once the -dev version is updated to release, I suspect the warning will go away.

**Comment by marcofacchetti** [comment] 2024-01-11 12:01
> commented

If I read correctly, version 8 is valid and no longer compatible and usable for Oracle database version 11. Correct?
Any suggestions other than upgrading the libraries to the latest version without migrating the database?

**Comment by alexkeh** [comment] 2024-01-11 14:54
@marcofacchetti That's correct. Oracle DB version 11 is out of support. The choices to remain supported are to stay with EFC 7 or earlier or upgrade the DB version.
