### ISSUE TITLE
[Scaffolding] Number(1) DEFAULT 0 NOT NULL generate bool? instead of bool

### ISSUE THREAD

**Issue by Guymestef** [oracle/dotnet-db-samples#147] opened 2021-02-26 11:00 UTC
Hello,

When I use dotnet ef dbcontext scaffold to generate an EF DbContext, the generated entities of the model contain nullable boolean instead of boolean for columns of type Number(1) DEFAULT 0 NOT NULL

```sql
  CREATE TABLE "TEST" 
   (	"ID" NUMBER(8,0) NOT NULL, 
	"TITLE" VARCHAR2(500 BYTE) NOT NULL, 
	"REVIEWED" NUMBER(1,0) DEFAULT 0 NOT NULL
   ) ;
```

This table should be translated to:
```C#
public partial class Test
{
        public Test()
        {
        }

        public int Id { get; set; }
        public string Title { get; set; }
        public bool Reviewed { get; set; }
}
```

Not to:

```C#
public partial class Test
{
        public Test()
        {
        }

        public int Id { get; set; }
        public string Title { get; set; }
        public bool? Reviewed { get; set; }
}
```

**Comment by alexkeh** [comment] 2021-02-26 17:06
Thanks for reporting. I've reproduced the issue and have created Bug 32560644 to track it and fix it.

**Comment by alexkeh** [comment] 2021-03-09 18:04
One of my team's EF Core developers performed some analysis on the issue.

This behavior is based on the Base Microsoft EF Core layer. There are a few GitHub issues filed against MS for this (i.e. forcing the property to be nullable when DEFAULT and NOT NULL constraints are both applied to a column). This appears unavoidable owing to how EFC and .NET handle default values for nullable and non-nullable CLR types. Thus, this is expected and not a bug.

The following links provide Microsoft’s reasoning why it is necessary to force the property to be nullable in case DEFAULT and NOT NULL both are applied to a column:

https://github.com/dotnet/efcore/issues/9507
https://forums.asp.net/t/2162598.aspx?Scaffold+DbContext+Such+a+column+is+mapped+to+a+nullable+bool+property+
https://stackoverflow.com/questions/60419069/ef-core-power-tools-generate-nullable-boolean

There is, however, a difference between Microsoft's EF Core and Oracle's EF Core provide implementation. In case the DEFAULT value is 0, MS EF Core will not force the property to be nullable, but Oracle still does. 

This has been the behavior in previous Oracle provider versions as well (2.x and 3.x). Because of that, Oracle cannot change it to match the MS provider in the current version (i.e. only force the property to be nullable if the DEFAULT is not 0), as it can potentially cause compilation issues in applications already using our provider.

Note the functionally of having a nullable property is the same as having a non-nullable property in this case. Since a DEFAULT constraint is applied to the column, NULL would never be inserted. Hence, we don’t have any functional issues as far as dealing with DB data is concerned.

For now, you can consider one of the two workarounds:
1.	Use the model with the nullable property, as it’s functionally same
2.	Manually alter the model to make the property non-nullable

We may consider making a change in a future release if there's a justified need to match the  MS EF Core settings when functionally the expected behavior occurs.

I'll close this issue, but the community can continue to post if they see a need for this enhancement request.

**Closed by alexkeh** 2021-03-09 18:04 UTC
