### ISSUE TITLE
Wrong statement generated for mapped function when using schema

### ISSUE THREAD

**Issue by ijanusic88** [oracle/dotnet-db-samples#255] opened 2022-09-19 08:15 UTC
We need to map a custom function to table-valued function. In the statement generated from EF, database schema is placed on the wrong place.

We are using Oracle.EntityFrameworkCore 6.21.61
Our configuration and mapping:

`public IQueryable<LoggedUser> GetName(int id)
	=> FromExpression(() => GetName(id));
	
modelBuilder
	.HasDbFunction(typeof(MyDbContext).GetMethod(nameof(MyDbContext.GetName), new[] { typeof(int) }))
	.HasName("GetName")
	.HasSchema("MySchema");`

It produces following SQL statement:
SELECT "g"."ID", "g"."FIRSTNAME", "g"."LASTNAME"
FROM "**MYSCHEMA**".table("GETNAME"(99)) "g"

But it should be:
SELECT "g"."ID", "g"."FIRSTNAME", "g"."LASTNAME"
FROM table("**MYSCHEMA**"."GETNAME"(99)) "g"

Exception:
"ORA-00903: Invalid Table Name"

**Comment by alexkeh** [comment] 2023-01-13 00:06
@ijanusic88 Sorry, I missed this post. Do you have a simple reproducible test case I can try this out to recreate the bug?

**Comment by alexkeh** [comment] 2023-11-06 20:11
Closing until we have a more complete test case to verify the bug and identify the root cause. I will reopen when we get a test case.

**Closed by alexkeh** 2023-11-06 20:11 UTC
