### ISSUE TITLE
Scaffold-DbContext To Tables from another schema

### ISSUE THREAD

**Issue by parejajd** [oracle/dotnet-db-samples#39] opened 2019-06-20 22:07 UTC
I try Scaffold tables that is stored in another schema, using the next command:

Scaffold-DbContext "Data Source=(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=X.X.X.X)(PORT=1521)))(CONNECT_DATA=(SID=MYSID)));User Id=MYUSER;Password=MYPASSWORD;" Oracle.EntityFrameworkCore -Tables "AnotherScheme.TheTable"

and i am getting:

**Unable to find a table in the database matching the selected table AnotherScheme.TheTable.**

I can make queries to the table.

**Comment by alexkeh** [comment] 2019-06-21 20:26
This is likely bug 29443379/28963848. This has been fixed post-beta 4, which means it will be in the production release.

**Closed by alexkeh** 2019-06-21 20:26 UTC

**Comment by pnmcosta** [comment] 2020-03-23 12:00
Hi @alexkeh,

I've just come across this problem, we're on netcoreapp2.2 and have the following packages installed:

```
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.2.6"/>
    <PackageReference Include="Oracle.EntityFrameworkCore" Version="2.19.60" />
    <PackageReference Include="Oracle.ManagedDataAccess.Core" Version="2.19.60" />
```

I'm new to Oracle and this packaged, could you confirm if it should be fixed on these versions? If not, could you confirm what the state of beta 4 is?

Thanks so much for your help in advance.

Cheers,
P.

**Comment by alexkeh** [comment] 2020-03-23 16:18
These bugs were fixed and are in the 2.19.60 release. You are likely running into another bug. Do you have a test case to share that we can use to reproduce the problem, find the root cause, and fix it?

**Comment by pnmcosta** [comment] 2020-03-23 16:54
Very similar to what's above, trying to auth with a user/schema that is diferent from the tables schema being used. It always says "Unable to find a table in the database matching the selected table". However, if I set "-Schemas: AnotherScheme" with the same connection string, it works fine, except it's scaffolding all the tables.

**Comment by alexkeh** [comment] 2020-03-23 19:07
Did you try using the "-Tables <list of tables>" format?

If you don't specify the specific tables, then all the schema's tables will be scaffolded.

**Comment by pnmcosta** [comment] 2020-03-24 08:56
yup, tried: 

`-Tables "AnotherScheme.TheTable"`

`-Tables "[AnotherScheme].[TheTable]"`

to no avail.

**Comment by alexkeh** [comment] 2020-03-24 19:11
I just tried it out with the -Schemas and -Tables parameters and it works if you use both of these. For example:
Scaffold-DbContext "<connection string>" Oracle.EntityFrameworkCore -Schemas <schema> -Tables <tables>

**Comment by pnmcosta** [comment] 2020-03-25 09:05
If i use both, -Tables seems to get ignored and ALL the tables under the -Schemas I determined get scaffolded.

**Comment by alexkeh** [comment] 2020-03-25 22:05
2.19.60 is the latest available versions of the Oracle providers.

Which Oracle DB version are you using? I tested with a 19c DB.

Can you provide the ODP.NET trace for when you scaffold? You can turn on tracing by setting the following properties in OnConfiguring() and using the Oracle.ManagedDataAccess.Client namespace.

```
OracleConfiguration.TraceLevel = 7;
OracleConfiguration.TraceFileLocation = @"D:\traces";
```
Can you also provide the verbose trace (-Verbose parameter) when you run Scaffold-DbContext command?

Between those two traces, we can see what ODP.NET EF Core and the scaffold command are doing to identify the root cause.

**Comment by pnmcosta** [comment] 2020-03-26 09:00
Hi Alex,

Thanks, I'll be sending you the verbose logs privately. The oracle version is 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production.

Cheers,
P.

**Comment by alexkeh** [comment] 2020-03-31 20:06
@pnmcosta 
Yes. You can send me the logs. alex.keh <at> oracle.com.

**Comment by lgoodw** [comment] 2020-04-30 08:32
@pnmcosta @alexkeh  Hi, I was just wondering if you were able to find the root cause of this issue in the end?  Thanks

**Comment by alexkeh** [comment] 2020-04-30 15:29
@lgoodw I haven't received a test case yet. Perhaps an email filter stopped if the project contained binaries.

**Comment by jwu-dharmo** [comment] 2020-05-10 15:02
I am using 2.19.60 and this works for me...for the schema name is case sensitive
scaffold-dbcontext -connection "Data Source=CNP3DEV;user id=<id>;Password=<pwd>" -provider oracle.entityframeworkcore -context GenspecsContext -schemas SYSDBA -Tables list of tables -dataannotations

**Comment by qianrunyu** [comment] 2023-05-03 04:26
Finally I figured out how to generate selected table by this command. You need to add double quote " to wrap the table name and don't add --schema at the same time. For example: 
dbcontext scaffold xxxxxx  -t "mySchema.table1"
If you use -t myShchema.table1 , the command prompt will return "couldn't find table" error
