### ISSUE TITLE
Oracle.ManagedDataAccess.dll Index was outside the bounds of the array

### ISSUE THREAD

**Issue by xiaoxiaomemg** [oracle/dotnet-db-samples#247] opened 2022-07-18 07:08 UTC
Hello!

Im using Oracle.ManagedDataAccess.Core v3.21.50 C# and getting error when trying to select data from DB 
 
For example:

command.CommandText = "SELECT EID,NOTICETYPE FROM NEWSADMIN.NP_BANK";

 using (OracleDataAdapter da = new OracleDataAdapter(command))
            {
                DataSet ds = new DataSet();
                try
                {
                    da.Fill(ds, "ds");
                    cmd.Parameters.Clear();
                }
                catch (OracleException ex)
                {
                    LogHelper.LogDebug($"QueryData-OracleException:{ex.Message}",ex);
                }
                finally
                {
                    cmd.Dispose();
                    //connection.Close();
                }
                return ds;
            }

Error message is "Index was outside the bounds of the array." And error code-" da.Fill(ds, "ds");"

**Comment by xiaoxiaomemg** [comment] 2022-07-20 02:59
> What DB version are you using? What data types are EID and NOTICETYPE?
> 
> Does the problem happen all the time, such as selecting zero rows, one row, and many rows? Does it require one of the data types to be of a particular size or have some particular characteristic?
> 
> If you can enable ODP.NET tracing and share that, it will speed up the diagnosis.

My Db version is Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production; And the EID and NOTICETYPE have the same data type with string. EID is the key.In addition to this,  they don't have other particular characteristic.

The problem hasppens occasionally, but once the problem appear, it will be often.  I have to restart this to slove the problem quickly , so I can't support the tracing now.(Restarted can temporarily slove thisproblem )

**Comment by alexkeh** [comment] 2022-07-20 06:45
The ODP.NET trace would be most informative. 

I've seen this type of error before when the table definition changes between queries. The cause is the statement cache that retains the metadata no longer accurately represents the table. The solution is turn off statement caching. Of course, that situation is rare since few apps perform DDL on their schema objects while their apps on running.

**Comment by alexkeh** [comment] 2022-07-27 14:00
I need more info to further investigate the problem. I will close this for now until I can get a trace or something else that could direct us to the root cause.

**Closed by alexkeh** 2022-07-27 14:00 UTC

**Comment by xiaoxiaomemg** [comment] 2022-10-08 07:57
Thank you  for your reply, It's indeed because the table structure has changed.
