### ISSUE TITLE
Scaffolding: Method not found: 'Microsoft.EntityFrameworkCore.WarningBehavior Microsoft.EntityFrameworkCore.Diagnostics.EventDefinitionBase.GetLogBehavior(Microsoft.EntityFrameworkCore.Diagnostics.IDiagnosticsLogger`1<!!0>)'.

### ISSUE THREAD

**Issue by mannok** [oracle/dotnet-db-samples#92] opened 2020-08-19 14:01 UTC
```
PS C:\projects\test\cs\TIS2.Textual> dotnet ef dbcontext scaffold "User Id=ts;Password=0000;Data Source=10.62.43.111:1526/pdb.ts.abc;" Oracle.EntityFrameworkCore --project TIS2.Textual.D
AL --startup-project EFCoreStartup --output-dir ../TIS2.Textual.Models/DTO --namespace TIS2.Textual.Models.DTO --context-dir ./DBContexts --context-namespace TIS2.Textual.DAL.DBContexts -f -v
```

```
Using project 'TIS2.Textual.DAL\TIS2.Textual.DAL.csproj'.
Using startup project 'EFCoreStartup\EFCoreStartup.csproj'.
Writing 'TIS2.Textual.DAL\obj\TIS2.Textual.DAL.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\mannok\AppData\Local\Temp\tmp4350.tmp /verbosity:quiet /nologo TIS2.Textual.DAL\TIS2.Textual.DAL.csproj
Writing 'EFCoreStartup\obj\EFCoreStartup.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\mannok\AppData\Local\Temp\tmp4881.tmp /verbosity:quiet /nologo EFCoreStartup\EFCoreStartup.csproj
Build started...
dotnet build EFCoreStartup\EFCoreStartup.csproj /verbosity:quiet /nologo
C:\projects\test\cs\TIS2.Textual\EFCoreStartup\EFCoreStartup.csproj : warning NU1608: Detected package version outside of dependency constraint: Oracle.EntityFrameworkCore 3.19.0-beta2 requires Microsoft.Entity
FrameworkCore.Relational (>= 3.1.5 && < 4.0.0) but version Microsoft.EntityFrameworkCore.Relational 5.0.0-preview.4.20220.10 was resolved.
C:\projects\test\cs\TIS2.Textual\EFCoreStartup\EFCoreStartup.csproj : warning NU1608: Detected package version outside of dependency constraint: Oracle.EntityFrameworkCore 3.19.0-beta2 requires Microsoft.Entity
FrameworkCore.Relational (>= 3.1.5 && < 4.0.0) but version Microsoft.EntityFrameworkCore.Relational 5.0.0-preview.4.20220.10 was resolved.
DBContexts\StockContext.cs(23,10): warning CS1030: #warning: 'To protect potentially sensitive information in your connection string, you should move it out of source code. See http://go.microsoft.com/fwlink/?LinkId
=723263 for guidance on storing connection strings.' [C:\projects\test\cs\TIS2.Textual\TIS2.Textual.DAL\TIS2.Textual.DAL.csproj]

Build succeeded.

C:\projects\test\cs\TIS2.Textual\EFCoreStartup\EFCoreStartup.csproj : warning NU1608: Detected package version outside of dependency constraint: Oracle.EntityFrameworkCore 3.19.0-beta2 requires Microsoft.Entity
FrameworkCore.Relational (>= 3.1.5 && < 4.0.0) but version Microsoft.EntityFrameworkCore.Relational 5.0.0-preview.4.20220.10 was resolved.
C:\projects\test\cs\TIS2.Textual\EFCoreStartup\EFCoreStartup.csproj : warning NU1608: Detected package version outside of dependency constraint: Oracle.EntityFrameworkCore 3.19.0-beta2 requires Microsoft.Entity
FrameworkCore.Relational (>= 3.1.5 && < 4.0.0) but version Microsoft.EntityFrameworkCore.Relational 5.0.0-preview.4.20220.10 was resolved.
DBContexts\StockContext.cs(23,10): warning CS1030: #warning: 'To protect potentially sensitive information in your connection string, you should move it out of source code. See http://go.microsoft.com/fwlink/?LinkId
=723263 for guidance on storing connection strings.' [C:\projects\test\cs\TIS2.Textual\TIS2.Textual.DAL\TIS2.Textual.DAL.csproj]
    3 Warning(s)
    0 Error(s)

Time Elapsed 00:00:02.91
Build succeeded.
dotnet exec --depsfile C:\projects\test\cs\TIS2.Textual\EFCoreStartup\bin\Debug\netcoreapp3.1\EFCoreStartup.deps.json --additionalprobingpath C:\Users\mannok\.nuget\packages --runtimeconfig C:\projects\test\cs\TIS2.Textual\EFCoreStartup\bin\Debug\netcoreapp3.1\EFCoreStartup.runtimeconfig.json C:\Users\mannok\.dotnet\tools\.store\dotnet-ef\5.0.0-preview.4.20220.10\dotnet-ef\5.0.0-preview.4.20220.10\tools\netco
reapp3.1\any\tools\netcoreapp2.0\any\ef.dll dbcontext scaffold "User Id=tis2app;Password=APP#0000;Data Source=10.62.43.111:1526/pdb.ts.abc;" Oracle.EntityFrameworkCore --output-dir ../TIS2.Textual.Mod
els/DTO --namespace TIS2.Textual.Models.DTO --context-dir ./DBContexts --context-namespace TIS2.Textual.DAL.DBContexts -f --assembly C:\projects\test\cs\TIS2.Textual\EFCoreStartup\bin\Debug\netcoreapp3.1\TIS2.T
extual.DAL.dll --startup-assembly C:\projects\test\cs\TIS2.Textual\EFCoreStartup\bin\Debug\netcoreapp3.1\EFCoreStartup.dll --project-dir C:\projects\test\cs\TIS2.Textual\TIS2.Textual.DAL\ --language C# --w
orking-dir C:\projects\test\cs\TIS2.Textual --verbose --root-namespace TIS2.Textual.DAL
Using assembly 'TIS2.Textual.DAL'.
Using startup assembly 'EFCoreStartup'.
Using application base 'C:\projects\test\cs\TIS2.Textual\EFCoreStartup\bin\Debug\netcoreapp3.1'.
Using working directory 'C:\projects\test\cs\TIS2.Textual\EFCoreStartup'.
Using root namespace 'TIS2.Textual.DAL'.
Using project directory 'C:\projects\test\cs\TIS2.Textual\TIS2.Textual.DAL\'.
Finding design-time services for provider 'Oracle.EntityFrameworkCore'...
Using design-time services from provider 'Oracle.EntityFrameworkCore'.
Finding design-time services referenced by assembly 'EFCoreStartup'.
No referenced design-time services were found.
Finding IDesignTimeServices implementations in assembly 'EFCoreStartup'...
Using design-time services from class 'EFDesignTimeService'.
2020-08-19 21:51:06.813079 ThreadID:1   (ENTRY)   OracleDatabaseModelFactory.ctor()
2020-08-19 21:51:06.815025 ThreadID:1   (EXIT)    OracleDatabaseModelFactory.ctor()
2020-08-19 21:51:06.919980 ThreadID:1   (ENTRY)   OracleDatabaseModelFactory.Create()
2020-08-19 21:51:07.847581 ThreadID:1   (ENTRY)   OracleDatabaseModelFactory.GetDefaultSchema()
2020-08-19 21:51:07.850396 ThreadID:1   (SQL)     OracleDatabaseModelFactory.GetDefaultSchema() : select sys_context('userenv', 'current_schema') from dual
2020-08-19 21:51:07.913792 ThreadID:1   (ERROR)   OracleDatabaseModelFactory.GetDefaultSchema() :  System.MissingMethodException: Method not found: 'Microsoft.EntityFrameworkCore.WarningBehavior Microsoft.EntityFram
eworkCore.Diagnostics.EventDefinitionBase.GetLogBehavior(Microsoft.EntityFrameworkCore.Diagnostics.IDiagnosticsLogger`1<!!0>)'.
   at Oracle.EntityFrameworkCore.Internal.OracleLoggerExtensions.DefaultSchemaFound(IDiagnosticsLogger`1 diagnostics, String schemaName)
   at Oracle.EntityFrameworkCore.Scaffolding.Internal.OracleDatabaseModelFactory.GetDefaultSchema(DbConnection connection)
2020-08-19 21:51:07.915125 ThreadID:1   (EXIT)    OracleDatabaseModelFactory.GetDefaultSchema()
2020-08-19 21:51:07.925994 ThreadID:1   (ERROR)   OracleDatabaseModelFactory.Create() :  System.MissingMethodException: Method not found: 'Microsoft.EntityFrameworkCore.WarningBehavior Microsoft.EntityFrameworkCore.
Diagnostics.EventDefinitionBase.GetLogBehavior(Microsoft.EntityFrameworkCore.Diagnostics.IDiagnosticsLogger`1<!!0>)'.
   at Oracle.EntityFrameworkCore.Internal.OracleLoggerExtensions.DefaultSchemaFound(IDiagnosticsLogger`1 diagnostics, String schemaName)
   at Oracle.EntityFrameworkCore.Scaffolding.Internal.OracleDatabaseModelFactory.GetDefaultSchema(DbConnection connection)
   at Oracle.EntityFrameworkCore.Scaffolding.Internal.OracleDatabaseModelFactory.Create(DbConnection connection, IEnumerable`1 tables, IEnumerable`1 schemas)
2020-08-19 21:51:07.928045 ThreadID:1   (EXIT)    OracleDatabaseModelFactory.Create()
System.MissingMethodException: Method not found: 'Microsoft.EntityFrameworkCore.WarningBehavior Microsoft.EntityFrameworkCore.Diagnostics.EventDefinitionBase.GetLogBehavior(Microsoft.EntityFrameworkCore.Diagnostics.
IDiagnosticsLogger`1<!!0>)'.
   at Oracle.EntityFrameworkCore.Internal.OracleLoggerExtensions.DefaultSchemaFound(IDiagnosticsLogger`1 diagnostics, String schemaName)
   at Oracle.EntityFrameworkCore.Scaffolding.Internal.OracleDatabaseModelFactory.GetDefaultSchema(DbConnection connection)
   at Oracle.EntityFrameworkCore.Scaffolding.Internal.OracleDatabaseModelFactory.Create(DbConnection connection, IEnumerable`1 tables, IEnumerable`1 schemas)
   at Oracle.EntityFrameworkCore.Scaffolding.Internal.OracleDatabaseModelFactory.Create(DbConnection connection, DatabaseModelFactoryOptions options)
   at Oracle.EntityFrameworkCore.Scaffolding.Internal.OracleDatabaseModelFactory.Create(String connectionString, DatabaseModelFactoryOptions options)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ReverseEngineerScaffolder.ScaffoldModel(String connectionString, DatabaseModelFactoryOptions databaseOptions, ModelReverseEngineerOptions modelOptions, ModelC
odeGenerationOptions codeOptions)
   at Microsoft.EntityFrameworkCore.Design.Internal.DatabaseOperations.ScaffoldContext(String provider, String connectionString, String outputDir, String outputContextDir, String dbContextClassName, IEnumerable`1 sc
hemas, IEnumerable`1 tables, String modelNamespace, String contextNamespace, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContextImpl(String provider, String connectionString, String outputDir, String outputDbContextDir, String dbContextClassName, IEnumerable`1 schema
Filters, IEnumerable`1 tableFilters, String modelNamespace, String contextNamespace, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContext.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Method not found: 'Microsoft.EntityFrameworkCore.WarningBehavior Microsoft.EntityFrameworkCore.Diagnostics.EventDefinitionBase.GetLogBehavior(Microsoft.EntityFrameworkCore.Diagnostics.IDiagnosticsLogger`1<!!0>)'.
```

Please see above codes. I can ensure the connection string is fine. How come I cannot scaffold my tables?

```
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="5.0.0-preview.4.20220.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="5.0.0-preview.4.20220.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.1.7" />
    <PackageReference Include="Oracle.EntityFrameworkCore" Version="3.19.0-beta2" />
```

**Comment by alexkeh** [comment] 2020-08-19 14:07
EF Core 5 is not yet supported. Duplicate of issue 81. https://github.com/oracle/dotnet-db-samples/issues/81

Use EF Core 3.1 for now. We will work on EF Core 5 support once we ship EF Core 3.1 in production.

**Closed by alexkeh** 2020-08-19 14:07 UTC
Labels: duplicate
