### ISSUE TITLE
Oracle.ManagedDataAccess.Core 3.21.100 references broken System.Directory.Protocols version

### ISSUE THREAD

**Issue by mus65** [oracle/dotnet-db-samples#285] opened 2023-04-24 14:37 UTC
After upgrading from 3.21.90 to 3.21.100 we got the following runtime error in our application when trying to connect to LDAP.

```
 ---> System.IO.FileLoadException: Could not load file or assembly 'System.DirectoryServices.Protocols, Version=6.0.0.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'System.DirectoryServices.Protocols, Version=6.0.0.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at OracleInternal.ConnectionPool.PoolManager`3.CreateNewPR(Int32 reqCount, Boolean bForPoolPopulation, ConnectionString csWithDiffOrNewPwd, OracleConnection connRefForCriteria, Boolean bMaxSemObtained, Boolean bIgnoreIdleSem, Boolean& bIdleSemObtainedWhileCreatingPR, String instanceName, List`1 switchFailedInstNames)
   at OracleInternal.ConnectionPool.OraclePoolManager.CreateNewPR(Int32 reqCount, Boolean bForPoolPopulation, ConnectionString csWithDiffOrNewPwd, OracleConnection connRefForCriteria, Boolean bMaxSemObtained, Boolean bIgnoreIdleSem, Boolean& bIdleSemObtainedWhileCreatingPR, String instanceName, List`1 switchFailedInstNames)
   at OracleInternal.ConnectionPool.PoolManager`3.Get(ConnectionString csWithDiffOrNewPwd, Boolean bGetForApp, OracleConnection connRefForCriteria, String affinityInstanceName, Boolean bForceMatch)
   at OracleInternal.ConnectionPool.OraclePoolManager.Get(ConnectionString csWithNewPassword, Boolean bGetForApp, OracleConnection connRefForCriteria, String affinityInstanceName, Boolean bForceMatch)
   at OracleInternal.ConnectionPool.OracleConnectionDispenser`3.Get(ConnectionString cs, PM conPM, ConnectionString pmCS, SecureString securedPassword, SecureString securedProxyPassword, OracleConnection connRefForCriteria)
```

This took quite some time to figure out, the actual issue is https://github.com/dotnet/runtime/issues/84031 . I'm not going into the technical details here, but the point is that System.DirectoryServices.Protocols 6.0.1 is broken in a way that makes applications referencing System.DirectoryServices.Protocols 7.0.0 fail at runtime with this exception.

While the actual issue is in System.DirectoryServices.Protocols 6.0.1, Microsoft obviously can't patch an already published Package. We currently downgraded to 3.21.90 which references the unaffected System.DirectoryServices.Protocols 5.0.1 .

It would be great if Oracle could fix this by either going back to 5.0.1 or requiring 7.0.0 . Until then, we are stuck with Oracle 3.21.90 .

**Comment by alexkeh** [comment] 2023-04-24 15:23
Customers can upgrade their System.DirectoryServices.Protocols to 7.0.0 themselves if needed. A 6.0.1 or higher version is needed in ODP.NET Core 21.10.

ODP.NET can't go back to System.DirectoryServices.Protocols 5.0.1 since there's a minimum .NET 6 requirement in some use cases.

MS could release a 6.0.2 version with a fix. The 6.x line is a long term release and should have regular patches when significant issues are discovered.

**Comment by mus65** [comment] 2023-04-24 15:42
> Customers can upgrade their System.DirectoryServices.Protocols to 7.0.0 themselves if needed. A 6.0.1 or higher version is needed in ODP.NET Core 21.10.

Please read the referenced issue. The whole point is that upgrading our application to 7.0.0 is what causes the problem. And we are forced to upgrade to 7.0.0 because of another dependency requiring it.

> ODP.NET can't go back to System.DirectoryServices.Protocols 5.0.1 since there's a minimum .NET 6 requirement in some use cases.
> 
> MS could release a 6.0.2 version with a fix. The 6.x line is a long term release and should have regular patches when significant issues are discovered.

Even if MS releases 6.0.2, Oracle would have to update their dependency to 6.0.2 to fix the issue.

**Comment by alexkeh** [comment] 2023-04-24 20:21
What Oracle does (and any other dependent vendors) depends on when and how MS will fixes the base bug.

**Comment by alexkeh** [comment] 2023-05-02 17:21
It looks like the [base bug fix will be released in mid-May](https://github.com/dotnet/runtime/issues/84031).

**Closed** 2023-05-10 02:43 UTC
Labels: Waiting on base bug/issue

**Comment by alexkeh** [comment] 2023-08-29 22:28
@mus65 Can you explain why ODP.NET Core's NuGet package needs to make System.DirectoryServices.Protocols to 6.0.2 mandatory for all users? 

I just created an app, installed ODP.NET Core 3.21.110, then upgraded System.DirectoryServices.Protocols to 6.0.2.

**Comment by Galad** [comment] 2023-09-11 15:49
Hi,
I agree with @mus65, the version of System.DirectoryServices.Protocols needs to be updated in the Oracle package because the assembly reference is currently incorrect.

To trigger the issue you need to actually make the Oracle lib to load System.DirectoryServices.Protocols. This can be achieved by retrieving all the types.

```csharp
_ = typeof(OracleConnection).Assembly.GetTypes();
```

See attached a solution where the issue can be reproduced.
[Oracle-System.Directory.Protocols-Repro.zip](https://github.com/oracle/dotnet-db-samples/files/12578113/Oracle-System.Directory.Protocols-Repro.zip)

**Comment by alexkeh** [comment] 2023-09-13 22:13
@mus65 We're not able to reproduce your issue. Can you provide a simple test case we can try out?

Once we have that, we can fix the issue and be assured that the patch will resolve the problem.

@Galad Your issue appears to be different as we can reproduce this issue with managed ODP.NET, not just with ODP.NET Core.

**Comment by alexkeh** [comment] 2023-09-14 19:45
@mus65 The test case appears to be the same as what @Galad has posted.

We believe these are two distinct issues as what @Galad's issue also occurs with managed ODP.NET, which doesn't have a System.DirectoryServices.Protocols dependency.

**Comment by alexkeh** [comment] 2023-09-15 21:07
The Oracle team has decided to bump the NuGet dependency for ODP.NET Core NuGet to use System.DirectoryServices.Protocols 6.0.2. This will occur in the next releases, 19.21 and 21.12 versions.
