### ISSUE TITLE
NET6 EF core wrong scaffolding.

### ISSUE THREAD

**Issue by tomasfil** [oracle/dotnet-db-samples#222] opened 2021-12-08 12:56 UTC
Hello, I will just post this issue from power tools repo:
https://github.com/ErikEJ/EFCorePowerTools/issues/1210

They way code gets auto generated for tables and views is wrong and wont allow the project to run.

**Comment by alexkeh** [comment] 2021-12-08 13:13
If more than one column is associated with any sequence/trigger, then ValueGeneratedOnAdd() Fluent API will be generated for each of these columns when performing a scaffolding operation. If we then use this scaffolded model to perform a migration, then an issue occurs. Each column associated with the ValueGeneratedOnAdd() Fluent API is made an identity column by default. To avoid this issue, use UseOracleSQLCompatibility("11") which will force Entity Framework Core to generate triggers/sequences instead.

**Comment by tomasfil** [comment] 2021-12-08 13:15
How do I use UseOracleSQLCompatibility("11") with EF Core power tools?

**Comment by alexkeh** [comment] 2021-12-08 13:24
`Scaffold-DbContext` would use the `UseOracle` method to configure DB connectivity. That's where the `UseOracleSQLCompatibility` method would be set. For example:

`optionsBuilder.UseOracle("User Id=<user>;Password=<password>;Data Source = inst1", b => b.UseOracleSQLCompatibility("11"));
`
My guess is that EF Core Power Tools will use the same API call and settings.

**Comment by tomasfil** [comment] 2021-12-08 14:00
![image](https://user-images.githubusercontent.com/34779382/145220223-e6ca0d1f-ab81-464e-915b-8f61bdbf5284.png)
![image](https://user-images.githubusercontent.com/34779382/145220428-06f899f5-8c6a-4b55-bea0-710ae84802c7.png)
![image](https://user-images.githubusercontent.com/34779382/145220456-9ad87b61-fb7c-4103-80b9-ea541093b4fe.png)
![image](https://user-images.githubusercontent.com/34779382/145220471-d208b31b-ff8e-4254-8e0e-8bc3220e391b.png)

And the output is still the same even with UseOracleSQLCompatibility setup and context cleared, so it recreated all entitites
![image](https://user-images.githubusercontent.com/34779382/145221037-fbd16ce0-6385-4bb9-a8f7-f4212e836769.png)

**Comment by tomasfil** [comment] 2021-12-08 14:27
When using:
```
Scaffold-DbContext "data source=source;user id=WMS;password=pwd" Oracle.EntityFrameworkCore -OutputDir Models -Context eWMSContext -ContextDir . -force
```
some work, but I still get error on some tables:
![image](https://user-images.githubusercontent.com/34779382/145225227-6a75d42a-0f51-4124-8846-57bfa7080408.png)

**Comment by tomasfil** [comment] 2021-12-08 14:58
I can confirm the same generated code with NET6 works on NET5:
![image](https://user-images.githubusercontent.com/34779382/145230278-6f15e35c-2469-478d-ab0a-0d46e8195fab.png)
![image](https://user-images.githubusercontent.com/34779382/145230317-2d81493c-feee-4fbe-87c4-c1728f7929cf.png)


But not NET6
![image](https://user-images.githubusercontent.com/34779382/145230516-64ab74d0-9cd9-4d28-8bce-00d5a9a425e2.png)
![image](https://user-images.githubusercontent.com/34779382/145230538-81dc54ee-6ef0-40c0-abb2-311659b30ae6.png)

**Comment by alexkeh** [comment] 2021-12-08 23:11
Thanks for the details. It does look like an Oracle EF Core 6 bug. I've created a bug (33652239) for the dev team to review the issue and try to fix it.

**Comment by tomasfil** [comment] 2021-12-09 07:01
@alexkeh Do you think there is way to fix manually the generated code please? I need to get it working

**Comment by alexkeh** [comment] 2021-12-09 16:57
First, we need to diagnose the problem. Once done, it will be clearer if a if a manual workaround is possible.

To track the bug, you need to have a [My Oracle Support](https://support.oracle.com/portal/) account. In general, the Oracle DBA maintains each customer's access to this site.

**Comment by tomasfil** [comment] 2021-12-10 07:05
I will have to wait for response here. I dont have access to company's customer oracle account.

Thanks, hope it will be fixed soon.

**Comment by alexkeh** [comment] 2021-12-15 12:25
Looks like the same issue also affects SQL Server's EF Core provider. It could be a generic issue.
https://github.com/dotnet/efcore/issues/27016

**Comment by tomasfil** [comment] 2021-12-15 13:14
What are the next steps then? Can I do anything to help out?

**Comment by alexkeh** [comment] 2021-12-15 14:04
We wait for an analysis from MS. If it turns out to be a generic EF Core 6 issue, we'll need to wait until it's patched. If it's something an EF Core provider can configure by the developer or provider writer, then we'll make adjustments as recommended.

**Comment by ErikEJ** [comment] 2022-01-06 08:04
The referenced EF Core issue is not related to this, it is not code generated by scaffolding. This is an Oracle provider issue.

**Comment by tomasfil** [comment] 2022-01-06 09:10
@alexkeh It seems it is on Oracle side. Thanks.

**Comment by alexkeh** [comment] 2022-01-06 17:42
@ErikEJ Oracle also doesn't allow more than one identity column per table. As Arthur notes,
> The fix is to explicitly specify some other way that one of the columns will get its generated value. This could be by specifying a value generator, or from a default value in the database. For example:

```
entity.Property(e => e.InterfaceHeaderId)
    .HasColumnName("INTERFACE_HEADER_ID")
    .HasDefaultValue(0m)
    .ValueGeneratedOnAdd();
```
What workaround gets generated for SQL Server with EF Core Power Tools? Our provider will likely emulate the same behavior if we can.

**Comment by ErikEJ** [comment] 2022-01-06 17:46
Power Tools does nothing in relation to this. As noted above the issue also occurs when using the command line tools.  I think you need a proper repro.

**Comment by alexkeh** [comment] 2022-01-06 18:09
That's right. I've asked @shvmgpt116 to provide his SQL Server table to MS to get confirmation of whether it's a bug or not. If not, we'll have confirmed what the new behavior should be. We can then emulate that in the Oracle provider.

**Comment by tomasfil** [comment] 2022-01-10 08:22
Hello @alexkeh . You can use my SQL to create the Table in this issue and you will have the exact same issue. (Oracle 11.2g)

**Comment by alexkeh** [comment] 2022-01-12 15:38
@tomasfil Can you provide the trigger script in your schema?

**Comment by tomasfil** [comment] 2022-01-13 07:56
@alexkeh Hello, this is the trigger:

We need to use this trigger, since 11.2 doesnt support identity columns.

```
CREATE OR REPLACE TRIGGER TRG_T_INV_ROUTING_HEADERS_INS
  BEFORE INSERT ON T_INVENTORY_ROUTING_HEADERS
  FOR EACH ROW
BEGIN
  SELECT SEQ_T_INV_ROUTING_HEADERS_ID.NEXTVAL INTO :new.id FROM dual;
END;
```

Just to note we have many more triggers on other tables doing business logic and not on just ID columns. Hope the triggers are not the issue.

**Comment by tomasfil** [comment] 2022-01-28 11:04
@alexkeh Hello, are there any news regarding this issue please?

**Comment by alexkeh** [comment] 2022-01-28 15:27
@tomasfil I've asked the dev team for an update.

cc: @shvmgpt116

**Comment by tomasfil** [comment] 2022-02-14 21:17
@alexkeh Hello, did you get any update back on the issue?

Thanks.

**Comment by alexkeh** [comment] 2022-02-15 03:15
@shvmgpt116 can you provide an update?

**Comment by tomasfil** [comment] 2022-03-01 13:34
Hello, this is taking very long time. What is actual status please? This is the only thing that keeps us from NET 6

**Comment by alexkeh** [comment] 2022-03-01 16:58
The bug is still in the developer's queue, but not fixed yet. If getting a fix is time critical, I recommend opening up an Oracle support service request and requesting the bug to be escalated. Moreover, you could request a one-off patch once the fix is complete. That way, you don't need to wait for the next quarterly patch.

We release new ODP.NET Core patches at least quarterly (and sometimes twice a quarter). Once the bug is fixed, depending on where we are in the patch release cycle, it could mean three months (or more*) before a quarterly patch with a fix makes it to NuGet Gallery. The one-off process allows you to get the patch much earlier.

* It's possible to be longer than three months if the fix misses the next patch's code freeze date.

**Comment by tomasfil** [comment] 2022-03-17 07:44
Well, it wont be even 3 months, sice this issue exists since May 2021. 

https://community.oracle.com/tech/developers/discussion/4484686/problem-scaffolding-oracledb-using-entityframeworkcore/p2

Was there even progress on that one?
It is exactly the same issue.

Oracle 11.2 doesnt have identity column, so the scaffolder pops 'ValueGeneratedOnAdd' on every single property.
```

            modelBuilder.Entity<TInventoryRoutingHeader>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedOnAdd();

                entity.Property(e => e.ApplRev).ValueGeneratedOnAdd();

                entity.Property(e => e.ApplRevDate).ValueGeneratedOnAdd();

                entity.Property(e => e.Attribute0).ValueGeneratedOnAdd();

                entity.Property(e => e.Attribute1).ValueGeneratedOnAdd();

                entity.Property(e => e.Attribute2).ValueGeneratedOnAdd();

                entity.Property(e => e.Attribute3).ValueGeneratedOnAdd();

                entity.Property(e => e.Attribute4).ValueGeneratedOnAdd();

                entity.Property(e => e.Final).ValueGeneratedOnAdd();

                entity.Property(e => e.InventoryRoutingTypesId).ValueGeneratedOnAdd();

                entity.Property(e => e.MoveGateId).ValueGeneratedOnAdd();

                entity.Property(e => e.PartyId).ValueGeneratedOnAdd();

                entity.Property(e => e.RequestTypeId).ValueGeneratedOnAdd();

                entity.Property(e => e.RoutingCost).ValueGeneratedOnAdd();

                entity.Property(e => e.RoutingDesc).ValueGeneratedOnAdd();

                entity.Property(e => e.RoutingName).ValueGeneratedOnAdd();

                entity.Property(e => e.UpdateBy).ValueGeneratedOnAdd();

                entity.Property(e => e.UpdateDate)
                    .ValueGeneratedOnAdd()
                    .HasDefaultValueSql("sysdate");

                entity.Property(e => e.Valid)
                    .ValueGeneratedOnAdd()
                    .HasDefaultValueSql("1");

                entity.Property(e => e.WindowsUser).ValueGeneratedOnAdd();
            });
```

Running into this error
```
System.InvalidOperationException: 
'The properties 
'TInventoryRoutingHeader.Id', 
'TInventoryRoutingHeader.Final', 
'TInventoryRoutingHeader.InventoryRoutingTypesId', 
'TInventoryRoutingHeader.MoveGateId', 
'TInventoryRoutingHeader.PartyId', 
'TInventoryRoutingHeader.RequestTypeId', 
'TInventoryRoutingHeader.RoutingCost', 
'TInventoryRoutingHeader.UpdateBy' 
are configured to use 'Identity' value generation and are mapped to the same table 'WMS.T_INVENTORY_ROUTING_HEADERS', 
but only one column per table can be configured as 'Identity'. 
Call 'ValueGeneratedNever' in 'OnModelCreating' for properties that should not use 'Identity'.'
```

**Comment by alexkeh** [comment] 2022-03-17 15:42
The bug has been fixed and will be in the next ODP.NET 21.6 patch release. I estimate that you'll see it on NuGet Gallery in April. If you need a fix sooner, please request a one-off fix via Oracle Support.

**Closed by alexkeh** 2022-03-17 15:42 UTC
Labels: bug

**Comment by MostAa7** [comment] 2022-04-07 12:18
When is the release date of the next ODP.NET 21.6 patch release?

**Comment by alexkeh** [comment] 2022-04-07 14:45
It should be this month.

**Comment by MostAa7** [comment] 2022-04-13 11:33
Any idea when. I need this for one of my projects.

**Comment by alexkeh** [comment] 2022-04-13 14:38
Sometime around the last week of this month.

**Comment by alexkeh** [comment] 2022-05-04 23:04
The patch is now available on NuGet Gallery.

**Comment by ErikEJ** [comment] 2022-05-05 08:28
Added to latest daily in EF Core Power Tools

**Comment by tomasfil** [comment] 2022-07-08 08:14
The issue is fixed partially.

Same thing happens when using `Scaffold-DbContext` with `-DataAnnotations` parameter
