### ISSUE TITLE
EF Core 3.1 Beta 2 - Difference between two Date columns

### ISSUE THREAD

**Issue by kakone** [oracle/dotnet-db-samples#84] opened 2020-07-21 15:14 UTC
With Oracle EF Core 3.1 Beta 2, when I try to do a difference between two Date columns :
```csharp
var row = (from r in dbContext.Entities select new { ElapsedTime = r.EndDate - r.StartDate }).FirstOrDefault();
```

I get a `System.InvalidCastException: 'Unable to cast object of type 'System.Decimal' to type 'System.TimeSpan'.'`

**Comment by alexkeh** [comment] 2020-07-21 18:25
This appears related to bug 31423881 that a customer reported on the [OTN ODP.NET forum](https://community.oracle.com/thread/4332557). This bug has been fixed, but missed making it into beta 2. The bug fix will be in the production release.

**Comment by rafaelpadovezi** [comment] 2020-07-21 20:13
@alexkeh I'm having the same problem. Can we use [DbFunctions](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbfunctions?view=efcore-3.1) as a workaround? Or `Oracle.EntityFrameworkCore` does not provide a implementation?

**Comment by alexkeh** [comment] 2020-07-21 20:28
I believe EF.Functions.Like is available, but we haven't implemented anything additional.

**Comment by rafaelpadovezi** [comment] 2020-07-22 12:51
When the difference between dates is in the `Where` clause the exception is different:

```csharp
context.Blog
    .Where(x => (DateTime.Today - x.CreateDate).Days < 20)
```

I get

```
System.InvalidOperationException : The LINQ expression 'DbSet<Blog>
    .Where(f => (DateTime.Today - f.CreateDate).Days < 20)' could not be translated.
```

**Comment by alexkeh** [comment] 2020-07-22 15:29
The error info may be different. The root cause remains the same.

**Comment by alexkeh** [comment] 2020-09-09 00:53
Production release is now available on [NuGet Gallery](https://www.nuget.org/packages/Oracle.EntityFrameworkCore/3.19.80).

**Closed by alexkeh** 2020-09-09 00:53 UTC
