### ISSUE TITLE
How to get the EXACT amount of rows Copied on a bulkcopy insert ?

### ISSUE THREAD

**Issue by rferraton** [oracle/dotnet-db-samples#367] opened 2024-03-13 22:51 UTC
It is quite surprising not to see a **RowsCopied** Property returned by the bulkcopy method and giving the total rows copied. It is the case on many other database .net clients (mssql, mysql, pgsql...)

Counting the target table is totally false in the case table already having data before bulk insert or long if the table is big and was empty.
So the example given is a little bit disappointing :
https://github.com/oracle/dotnet-db-samples/blob/95b7321c6510d07884a5160f2c81b4fc79977ec2/samples/bulk-copy/oracle-bulk-copy.cs#L54

Currently i use the **OracleRowsCopied** EventHandler BUT it seams that it is triggered only after a number of rows bulked. This number is determined by the **NotifyAfter** Property.

```csharp
obc.NotifyAfter = 10000;
long crows = 0;
obc.OracleRowsCopied += (sender, args) =>
{
   crows = args.RowsCopied;						
};
```

The problem is that the remaining rows between the last OracleRowsCopied Event and the final rows are not "detected".

Is there another method (and if possible avoiding to set NotifyAfter=1)

**Comment by alexkeh** [comment] 2024-03-14 00:04
@rferraton Once your BulkCopy operation completes, can't you retrieve the RowsCopied and perform a mod 1000 operation to find out the "remainder" of rows copied?

**Comment by rferraton** [comment] 2024-03-14 22:12
> @rferraton Once your BulkCopy operation completes, can't you retrieve the RowsCopied and perform a mod 1000 operation to find out the "remainder" of rows copied?

No, i don't get how you can find the exact using this technic. 

I think personnaly there is a lack\bug in the trigger that don't raise at the end of the load

**Comment by alexkeh** [comment] 2024-03-15 03:52
The [SqlBulkCopy NotifyAfter](https://learn.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlbulkcopy.notifyafter?view=dotnet-plat-ext-8.0) documentation says: "This property is designed for user interface components that illustrate the progress of a bulk copy operation. It indicates the number of rows to be processed before generating a notification event."

By design, NotifyAfter does not trigger at the end of the load operation necessarily based on MS's definition. ODP.NET follows that same behavior.

Here's what I mean about using the mod operation.
```
obc.NotifyAfter = 10000;
long crows = 0;
obc.OracleRowsCopied += (sender, args) =>
{
   crows = args.RowsCopied;						
};

// Use mod operator to record the remaining rows that were bulk copied after the last NotifyAfter event.
short extraRows = crows % 10000;
// Trigger event to output extraRows value.
```

**Comment by rferraton** [comment] 2024-03-16 20:26
No you solution does not work. (tested)

Let's imagine you have 5 rows to load and **NotifyAfter** is set to 1000

```csharp
obc.OracleRowsCopied += (sender, args) =>
{
   crows = args.RowsCopied;						
};
```
will never by trigered ==> crows will remain equal to 0
extraRows = 0

**Comment by alexkeh** [comment] 2024-03-17 15:34
It's possible you're hitting bug 34248388. This bug reset the RowsCopied value after every NotifyAfter. Which ODP.NET version and type are you using? 

This bug was fixed in ODP.NET 21.12. The fix is also available in the latest ODP.NET 19c version as well. Try upgrading to the latest ODP.NET version if you're not already using it. If this is a new bug, can you publish a full test case and indicate the versions of ODP.NET and DB you are using?

**Comment by rferraton** [comment] 2024-03-18 22:07
i used the 3.21.130 and now the 23.2.2-dev : same problem

**Comment by alexkeh** [comment] 2024-03-20 01:17
After reviewing the APIs with the dev team, we've concluded this issue is not a bug. ODP.NET's definition for [NotifyAfter](https://docs.oracle.com/en/database/oracle/oracle-database/23/odpnt/BulkCopyNotifyAfter.html#GUID-B7E22811-8A26-457C-A825-2C467B58D16E) is similar to SqlClient's in that the property is intended for UI components to measure progress. 

> This property can be retrieved in user interface components to display the progress of a bulk copy operation.

For [ODP.NET RowsCopied](https://docs.oracle.com/en/database/oracle/oracle-database/23/odpnt/BulkCopyOracleRowsCopied.html#GUID-F7736BFF-2C44-4F0D-BB1C-A7F8AA98D36B), the description states 

> This event is raised when the number of rows specified by the NotifyAfter property has been processed. It does not imply that the rows have been sent to the database or committed.

This is similar to [SqlClient RowsCopied](https://learn.microsoft.com/en-us/dotnet/api/microsoft.data.sqlclient.sqlbulkcopy.rowscopied?view=sqlclient-dotnet-standard-5.1) property, which states

> This value is incremented during the SqlRowsCopied event and does not imply that this number of rows has been sent to the server or committed.

Based on the doc, the ODP.NET APIs are behaving as documented and matches ADO.NET's intent.

With that said, we do see value for this feature request. We are considering adding a new API that triggers an event after all rows are copied. If that API is used, we could populate RowsCopied with the total number of rows copied.

Thus, we're making this bug an ER instead.

**Comment by rferraton** [comment] 2024-03-20 20:25
Thanks to push to DevTeam 👍 

Agree :  OracleRowsCopied Event have the behavior describe in the documentation.
Agree : at the time of writing, there is no way to know the exact number of row copied by the bulkCopy. This is not a bug but a lack ==> ER could be a good idea

Personnaly i prefer a gettable property instead of an event. I found "property way" more readable and safer with multiple-threads.

**Comment by alexkeh** [comment] 2024-05-31 17:33
Looks like we'll get this change in sooner than expected. It will be part of ODP.NET 23.5, as well as 21.15 and 19.24.

**Comment by alexkeh** [comment] 2024-07-11 21:08
ODP.NET 23.5 is now available.

**Closed by alexkeh** 2024-07-11 21:08 UTC
Labels: enhancement, question

**Comment by rferraton** [comment] 2025-03-17 15:41
Do you have an exemple for usage of the feature ?

**Comment by alexkeh** [comment] 2025-03-17 16:39
There's an ODP.NET NotifyAllRowsProcessed and Notify after code sample at the bottom of the [OracleBulkCopyOptions Enumeration page.](https://docs.oracle.com/en/database/oracle/oracle-database/23/odpnt/OracleBulkCopyOptionsEnumeration.html#GUID-72863EF2-A7C7-4B2F-A54B-AFAD4F61FD1B)

**Comment by rferraton** [comment] 2025-03-17 20:24
Sorry @alexkeh but the example provide in the documentation does not work :-(

the **OracleRowsCopiedEventHandler** constructor take "OnSqlRowsCopied" as input but it is quite obscur for me. What **OnSqlRowsCopied** is ?

The example in the documentatoin : 
```csharp
// Set up the bulk copy object so that it will notify the app when all rows have been copied.
using (OracleBulkCopy bulkCopy = new OracleBulkCopy(destinationConnection, OracleBulkCopyOption.NotifyAllRowsProcessed))
{
  bulkCopy.DestinationTableName = "BLOGS";
 
  try
  {
    // Write rows from the source to the destination.
    bulkCopy.NotifyAfter = 5;
    bulkCopy.OracleRowsCopied += new OracleRowsCopiedEventHandler(OnSqlRowsCopied);
    bulkCopy.WriteToServer(reader);
  }
  catch (Exception ex)
  {
    Console.WriteLine(ex.Message);
  }
  finally
  {
    // Close the OracleDataReader. The OracleBulkCopy object is automatically closed at the end of the using block.
    reader.Close();
  }
}

```



As alternative I propose this :

```csharp
   long crows=0;
   bulkCopy.OracleRowsCopied += (reader, args) => { crows = args.RowsCopied; };
```

instead of 

```csharp
    bulkCopy.OracleRowsCopied += new OracleRowsCopiedEventHandler(OnSqlRowsCopied);
```

The feature, in itself, with the **NotifyAllRowsProcessed** works correctly

**Comment by alexkeh** [comment] 2025-03-17 23:27
@rferraton 

The sample code is a code snippet. 

`OnSqlRowsCopied` is the name of the event handler delegate, which a developer would create. 

The delegate code is not shown since its purpose is not critical to the sample's purpose. The sample shows how to use `NotifyAllRowsProcessed` and that it can be used in parallel with `NotifyAfter`.

**Comment by rferraton** [comment] 2025-03-18 14:46
OK got it ! Even if an self-supporting snippet would seam to me more easy to understand :-)

**Comment by alexkeh** [comment] 2025-03-19 03:26
We'll update the sample to make it clearer what `OnSqlRowsCopied` is. Thanks for the feedback!
