### ISSUE TITLE
Hang occurred in OracleInternal.Network.ReaderStream.ProcessOB

### ISSUE THREAD

**Issue by davidpayne** [oracle/dotnet-db-samples#407] opened 2024-08-13 00:28 UTC
I am using Oracle.ManagedDataAccess version 23.5.0 after recently updating from 21.10.0.

I don't think I've seen this issue in 21.10.0.

I've only seen it occur in version 23.5.0 and it's not reproducible with a cut down list of steps. It seems to occur rarely under heavy load.

The process running the code had a CPU usage of 25% even though it didn't appear to be doing anything.

One thread is stuck in a loop in this method:
```
Oracle.ManagedDataAccess.dll!OracleInternal.Network.ReaderStream.ProcessOB(OracleInternal.Network.OraBuf OB, bool bAsync) Line 312	C#
Oracle.ManagedDataAccess.dll!OracleInternal.Network.ReaderStream.ReadwithCrypto(OracleInternal.Network.OraBuf OB, bool bAsync) Line 602	C#
Oracle.ManagedDataAccess.dll!OracleInternal.Network.ReaderStream.Read(OracleInternal.Network.OraBuf OB, out int InbandErr, out string InbandErrMsg) Line 548	C#
Oracle.ManagedDataAccess.dll!OracleInternal.TTC.OraBufReader.GetDataFromNetwork(bool bAsync) Line 681	C#
Oracle.ManagedDataAccess.dll!OracleInternal.TTC.OraBufReader.Read(bool bAsync, bool bIgnoreData) Line 520	C#
Oracle.ManagedDataAccess.dll!OracleInternal.TTC.TTCOPing.ReadResponse() Line 49	C#
Oracle.ManagedDataAccess.dll!OracleInternal.ServiceObjects.OracleConnectionImpl.PingServer()	C#
Oracle.ManagedDataAccess.dll!OracleInternal.ServiceObjects.OracleConnectionImpl.FlushPendingPiggybackMessages(bool bInvokedOnAppThread)	C#
Oracle.ManagedDataAccess.dll!OracleInternal.ServiceObjects.OracleConnectionImpl.FlushPiggybacksTimerCallback(object source)	C#
mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
mscorlib.dll!System.Threading.TimerQueueTimer.CallCallback()	Unknown
mscorlib.dll!System.Threading.TimerQueueTimer.Fire()	Unknown
mscorlib.dll!System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()	Unknown
mscorlib.dll!System.Threading.ThreadPoolWorkQueue.Dispatch()	Unknown
```

And this thread appears to be waiting for a result from the first thread:

```mscorlib.dll!System.Threading.SemaphoreSlim.WaitUntilCountOrTimeout(int millisecondsTimeout, uint startTime, System.Threading.CancellationToken cancellationToken)	Unknown
mscorlib.dll!System.Threading.SemaphoreSlim.Wait(int millisecondsTimeout, System.Threading.CancellationToken cancellationToken)	Unknown
Oracle.ManagedDataAccess.dll!OracleInternal.ServiceObjects.OracleConnectionImpl.WaitForConnectionForExecution(bool noCancellation, OracleInternal.ServiceObjects.OracleCommandImpl cmdImpl, bool bPipeliningLocks, bool bAsync)	C#
Oracle.ManagedDataAccess.dll!OracleInternal.ServiceObjects.OracleCommandImpl.ExecuteReader(string commandText, Oracle.ManagedDataAccess.Client.OracleParameterCollection paramColl, System.Data.CommandType commandType, OracleInternal.ServiceObjects.OracleConnectionImpl connectionImpl, int longFetchSize, long clientInitialLOBFS, OracleInternal.ServiceObjects.OracleDependencyImpl orclDependencyImpl, long[] scnForExecution, long internalInitialJSONFS, Oracle.ManagedDataAccess.Client.OracleConnection connection, OracleInternal.ServiceObjects.OracleCommandImpl.ER_RefAndOutParamArgCtx er_refOutCtx, bool isDescribeOnly, bool isFromEF, bool bAsync) Line 4795	C#
Oracle.ManagedDataAccess.dll!Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteReaderInternal(bool requery, bool fillRequest, System.Data.CommandBehavior behavior, bool bAsync) Line 4142	C#
Oracle.ManagedDataAccess.dll!Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteScalarInternal(bool bAsync) Line 4363	C#
Oracle.ManagedDataAccess.dll!Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteScalar() Line 3327	C#
```

**Comment by alexkeh** [comment] 2024-08-13 01:55
For hard to reproduce hangs, we'll need much more in-depth diagnostic info to identify the root cause. I recommend opening up an Oracle Support service request to be able to do this deeper analysis. Two more reasons to go the SR route is that is the way Oracle can share enhanced diagnostic drops and validations drops.

Enhanced diagnostics collect more internal trace info if the standard trace is inadequate.

Once a fix is identified and implemented, the validation drop can be tested in your environment to ensure it actually fixes the problem.

**Comment by davidpayne** [comment] 2024-08-13 03:10
Thanks, I also have a dump file which I can share with Oracle Support.

**Comment by alexkeh** [comment] 2024-08-14 02:26
Closing. The next step is to open an SR for Oracle Support to analyze the dump and collect more diagnostics.

**Closed by alexkeh** 2024-08-14 02:26 UTC
