### ISSUE TITLE
Oracle.ManagedDataAccess.Client.OracleException (0x80004005): ORA-28040: The database does not accept your client's authentication protocol; login denied.

### ISSUE THREAD

**Issue by murat16ertekin** [oracle/dotnet-db-samples#386] opened 2024-05-31 08:27 UTC
Hello;

In our project where we work with Oracle 12c version and in our project developed with .Net 8;
I upgraded the Oracle.EntityFrameworkCore version from 8.21.140 to 8.23.40 and started getting errors when connecting to the database. The error is caused by outdated Oracle versions being out of support by default.

![Oracle EntityFrameworkCore-Issue-1](https://github.com/oracle/dotnet-db-samples/assets/20865216/9bba5141-54f6-4d98-83bb-77fb8e9492e3)

**Comment by murat16ertekin** [comment] 2024-05-31 08:31
When the client version is set in the OnConfiguring method in the DbContext class, the connection is established once and then it gives an error again.

OracleConfiguration.SqlNetAllowedLogonVersionClient = OracleAllowedLogonVersionClient."ORACLE_VERSION"


![Oracle EntityFrameworkCore-Issue-2-1](https://github.com/oracle/dotnet-db-samples/assets/20865216/a9e648a1-6338-455d-b3b9-a1e3397a7001)


![Oracle EntityFrameworkCore-Issue-2](https://github.com/oracle/dotnet-db-samples/assets/20865216/26dedd51-ea82-4ca8-841b-e6ccaabe7600)

**Comment by murat16ertekin** [comment] 2024-05-31 08:35
The problem was solved when the client version was set in the OnModelCreating method in the DbContext class.

OracleConfiguration.SqlNetAllowedLogonVersionClient = OracleAllowedLogonVersionClient.ORACLE_VERSION


![Oracle EntityFrameworkCore-Issue-2-2](https://github.com/oracle/dotnet-db-samples/assets/20865216/b7e6c468-ea3c-4654-aa33-0969a80b72ef)

**Comment by alexkeh** [comment] 2024-05-31 15:02
Duplicate of https://github.com/oracle/dotnet-db-samples/issues/379

Happy to see you were able to resolve the issue.

**Closed by alexkeh** 2024-05-31 15:02 UTC
Labels: duplicate, question

**Comment by RonaldChonillo** [comment] 2024-09-20 17:55
Doesn't work for me.... .netcore 8

**Comment by alexkeh** [comment] 2024-09-20 19:06
@RonaldChonillo Do you want to share the errors, code, DB and client relevant configuration info, and what solutions you tried? If ODP.NET worked before in the same setup, what version did you use?
